import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFDF9",
  },
  header: {
    paddingTop: 60,
    paddingBottom: 28,
    paddingHorizontal: 20,
    alignItems: "center",
  },
  backButton: {
    position: "absolute",
    top: 56,
    left: 16,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.6)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "rgba(255,255,255,0.85)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#4A2A33",
  },
  headerSubtitle: {
    fontSize: 13,
    color: "#6B4C55",
    marginTop: 4,
    textAlign: "center",
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  priceCard: {
    alignItems: "center",
    backgroundColor: "#FFF3F5",
    borderRadius: 16,
    paddingVertical: 20,
    marginTop: 20,
    borderWidth: 1,
    borderColor: "#FFD8E0",
  },
  priceValue: {
    fontSize: 32,
    fontWeight: "800",
    color: "#FF4D6D",
  },
  pricePeriod: {
    fontSize: 13,
    color: "#8D6171",
    marginTop: 2,
  },
  priceNote: {
    fontSize: 12,
    color: "#B08A94",
    marginTop: 6,
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: "#8D6171",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: 24,
    marginBottom: 10,
  },
  featureTableHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingBottom: 8,
  },
  featureTableHeaderLabel: {
    flex: 1,
  },
  featureTableHeaderCol: {
    width: 56,
    textAlign: "center",
    fontSize: 12,
    fontWeight: "600",
    color: "#8D6171",
  },
  featureTableHeaderColPremium: {
    color: "#FF4D6D",
  },
  featureList: {
    borderTopWidth: 1,
    borderTopColor: "#F5E4E8",
  },
  featureRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F5E4E8",
  },
  featureLabelWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  featureIconCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#FFE6EB",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  featureLabel: {
    fontSize: 14,
    color: "#4A2A33",
    flexShrink: 1,
  },
  featureCheckCol: {
    width: 56,
    alignItems: "center",
  },
  footer: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 28,
    backgroundColor: "#FFFDF9",
    borderTopWidth: 1,
    borderTopColor: "#F5E4E8",
  },
  upgradeButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FF4D6D",
    borderRadius: 14,
    paddingVertical: 15,
    gap: 8,
  },
  upgradeButtonDisabled: {
    opacity: 0.7,
  },
  upgradeButtonText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "700",
  },
});