import {
  Building2,
  Camera,
  Video,
  Flower2,
  Sparkles,
  Hand,
  UtensilsCrossed,
  Cake,
  Music2,
  Drum,
  PartyPopper,
  HeartHandshake,
  CarFront,
  Hotel,
  Mail,
  Shirt,
  Gem,
  Flower,
  Landmark,
} from "lucide-react";

export const serviceCategories = [
  {
    id: 1,
    title: "Venue",
    icon: Building2,
    vendors: "250+ Vendors",
    href: "/vendors?category=Venue",
  },
  {
    id: 2,
    title: "Photographer",
    icon: Camera,
    vendors: "180+ Vendors",
    href: "/vendors?category=Photographer",
  },
  {
    id: 3,
    title: "Videographer",
    icon: Video,
    vendors: "140+ Vendors",
    href: "/vendors?category=Videographer",
  },
  {
    id: 4,
    title: "Decorator",
    icon: Flower2,
    vendors: "150+ Vendors",
    href: "/vendors?category=Decorator",
  },
  {
    id: 5,
    title: "Makeup Artist",
    icon: Sparkles,
    vendors: "210+ Vendors",
    href: "/vendors?category=Makeup Artist",
  },
  {
    id: 6,
    title: "Mehendi Artist",
    icon: Hand,
    vendors: "120+ Vendors",
    href: "/vendors?category=Mehendi Artist",
  },
  {
    id: 7,
    title: "Caterer",
    icon: UtensilsCrossed,
    vendors: "200+ Vendors",
    href: "/vendors?category=Caterer",
  },
  {
    id: 8,
    title: "Cake Designer",
    icon: Cake,
    vendors: "80+ Vendors",
    href: "/vendors?category=Cake Designer",
  },
  {
    id: 9,
    title: "DJ",
    icon: Music2,
    vendors: "90+ Vendors",
    href: "/vendors?category=DJ",
  },
  {
    id: 10,
    title: "Live Band",
    icon: Drum,
    vendors: "60+ Vendors",
    href: "/vendors?category=Live Band",
  },
  {
    id: 11,
    title: "Entertainment",
    icon: PartyPopper,
    vendors: "75+ Vendors",
    href: "/vendors?category=Entertainment",
  },
  {
    id: 12,
    title: "Wedding Planner",
    icon: HeartHandshake,
    vendors: "140+ Vendors",
    href: "/vendors?category=Wedding Planner",
  },
  {
    id: 13,
    title: "Transportation",
    icon: CarFront,
    vendors: "65+ Vendors",
    href: "/vendors?category=Transportation",
  },
  {
    id: 14,
    title: "Accommodation",
    icon: Hotel,
    vendors: "50+ Vendors",
    href: "/vendors?category=Accommodation",
  },
  {
    id: 15,
    title: "Invitation Designer",
    icon: Mail,
    vendors: "55+ Vendors",
    href: "/vendors?category=Invitation Designer",
  },
  {
    id: 16,
    title: "Bridal Wear",
    icon: Shirt,
    vendors: "130+ Vendors",
    href: "/vendors?category=Bridal Wear",
  },
  {
    id: 17,
    title: "Groom Wear",
    icon: Shirt,
    vendors: "90+ Vendors",
    href: "/vendors?category=Groom Wear",
  },
  {
    id: 18,
    title: "Jewellery",
    icon: Gem,
    vendors: "95+ Vendors",
    href: "/vendors?category=Jewellery",
  },
  {
    id: 19,
    title: "Florist",
    icon: Flower,
    vendors: "85+ Vendors",
    href: "/vendors?category=Florist",
  },
  {
    id: 20,
    title: "Pandit / Priest",
    icon: Landmark,
    vendors: "40+ Vendors",
    href: "/vendors?category=Pandit / Priest",
  },
];