import { AdminRole } from '@prisma/client';

export const ADMIN_PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',
  ADMINS_MANAGE: 'admins.manage',
  AUDIT_VIEW: 'audit.view',
  VENDORS_VIEW: 'vendors.view',
  VENDORS_MANAGE: 'vendors.manage',
  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMERS_MANAGE: 'customers.manage',
  BOOKINGS_VIEW: 'bookings.view',
  BOOKINGS_MANAGE: 'bookings.manage',
  PREMIUM_PLANNING_VIEW: 'premium-planning.view',
  PREMIUM_PLANNING_MANAGE: 'premium-planning.manage',
  PAYMENTS_VIEW: 'payments.view',
  PAYMENTS_APPROVE: 'payments.approve',
  PAYOUTS_RELEASE: 'payouts.release',
  REFUNDS_MANAGE: 'refunds.manage',
  REVIEWS_VIEW: 'reviews.view',
  REVIEWS_MANAGE: 'reviews.manage',
  CHAT_VIEW: 'chat.view',
  CHAT_MODERATE: 'chat.moderate',
  ACCOUNTS_SUSPEND: 'accounts.suspend',
  CONTENT_VIEW: 'content.view',
  CONTENT_MANAGE: 'content.manage',
  NOTIFICATIONS_VIEW: 'notifications.view',
  NOTIFICATIONS_MANAGE: 'notifications.manage',
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_MANAGE: 'settings.manage',
  REPORTS_VIEW: 'reports.view',
  EMAILS_VIEW: 'emails.view',
} as const;

export type AdminPermission =
  (typeof ADMIN_PERMISSIONS)[keyof typeof ADMIN_PERMISSIONS];

export const ALL_ADMIN_PERMISSIONS = Object.values(
  ADMIN_PERMISSIONS,
) as AdminPermission[];

export const ADMIN_ROLE_PERMISSIONS: Record<
  AdminRole,
  AdminPermission[]
> = {
  [AdminRole.SUPER_ADMIN]: ALL_ADMIN_PERMISSIONS,
  [AdminRole.FINANCE_ADMIN]: [
    ADMIN_PERMISSIONS.DASHBOARD_VIEW,
    ADMIN_PERMISSIONS.BOOKINGS_VIEW,
    ADMIN_PERMISSIONS.PAYMENTS_VIEW,
    ADMIN_PERMISSIONS.PAYMENTS_APPROVE,
    ADMIN_PERMISSIONS.PAYOUTS_RELEASE,
    ADMIN_PERMISSIONS.REFUNDS_MANAGE,
    ADMIN_PERMISSIONS.REPORTS_VIEW,
    ADMIN_PERMISSIONS.EMAILS_VIEW,
  ],
  [AdminRole.VENDOR_MANAGER]: [
    ADMIN_PERMISSIONS.DASHBOARD_VIEW,
    ADMIN_PERMISSIONS.VENDORS_VIEW,
    ADMIN_PERMISSIONS.VENDORS_MANAGE,
    ADMIN_PERMISSIONS.BOOKINGS_VIEW,
    ADMIN_PERMISSIONS.REVIEWS_VIEW,
  ],
  [AdminRole.BOOKING_MANAGER]: [
    ADMIN_PERMISSIONS.DASHBOARD_VIEW,
    ADMIN_PERMISSIONS.BOOKINGS_VIEW,
    ADMIN_PERMISSIONS.BOOKINGS_MANAGE,
    ADMIN_PERMISSIONS.PAYMENTS_VIEW,
    ADMIN_PERMISSIONS.CUSTOMERS_VIEW,
    ADMIN_PERMISSIONS.VENDORS_VIEW,
  ],
  [AdminRole.PREMIUM_PLANNING_MANAGER]: [
    ADMIN_PERMISSIONS.DASHBOARD_VIEW,
    ADMIN_PERMISSIONS.PREMIUM_PLANNING_VIEW,
    ADMIN_PERMISSIONS.PREMIUM_PLANNING_MANAGE,
  ],
  [AdminRole.SUPPORT_ADMIN]: [
    ADMIN_PERMISSIONS.DASHBOARD_VIEW,
    ADMIN_PERMISSIONS.CUSTOMERS_VIEW,
    ADMIN_PERMISSIONS.CUSTOMERS_MANAGE,
    ADMIN_PERMISSIONS.BOOKINGS_VIEW,
    ADMIN_PERMISSIONS.VENDORS_VIEW,
    ADMIN_PERMISSIONS.NOTIFICATIONS_VIEW,
    ADMIN_PERMISSIONS.NOTIFICATIONS_MANAGE,
  ],
  [AdminRole.CONTENT_MANAGER]: [
    ADMIN_PERMISSIONS.DASHBOARD_VIEW,
    ADMIN_PERMISSIONS.CONTENT_VIEW,
    ADMIN_PERMISSIONS.CONTENT_MANAGE,
  ],
  [AdminRole.REVIEW_DISPUTE_MANAGER]: [
    ADMIN_PERMISSIONS.DASHBOARD_VIEW,
    ADMIN_PERMISSIONS.REVIEWS_VIEW,
    ADMIN_PERMISSIONS.REVIEWS_MANAGE,
    ADMIN_PERMISSIONS.BOOKINGS_VIEW,
    ADMIN_PERMISSIONS.CUSTOMERS_VIEW,
    ADMIN_PERMISSIONS.VENDORS_VIEW,
  ],
  [AdminRole.CHAT_MODERATOR]: [
    ADMIN_PERMISSIONS.DASHBOARD_VIEW,
    ADMIN_PERMISSIONS.CHAT_VIEW,
    ADMIN_PERMISSIONS.CHAT_MODERATE,
    ADMIN_PERMISSIONS.CUSTOMERS_VIEW,
  ],
};

export const ADMIN_ROLE_LABELS: Record<AdminRole, string> = {
  [AdminRole.SUPER_ADMIN]: 'Super Admin',
  [AdminRole.FINANCE_ADMIN]: 'Finance Admin',
  [AdminRole.VENDOR_MANAGER]: 'Vendor Manager',
  [AdminRole.BOOKING_MANAGER]: 'Booking Manager',
  [AdminRole.PREMIUM_PLANNING_MANAGER]: 'Premium Planning Manager',
  [AdminRole.SUPPORT_ADMIN]: 'Support Admin',
  [AdminRole.CONTENT_MANAGER]: 'Content Manager',
  [AdminRole.REVIEW_DISPUTE_MANAGER]: 'Review & Dispute Manager',
  [AdminRole.CHAT_MODERATOR]: 'Chat Moderator',
};
