import { StyleSheet } from "react-native";

const shadow = {
  shadowColor: "#FF4D6D",
  shadowOpacity: 0.07,
  shadowRadius: 10,
  shadowOffset: { width: 0, height: 4 },
  elevation: 2,
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#FFF5F7" },
  scrollContent: { paddingTop: 10, paddingBottom: 40 },
  heroCard: {
    marginHorizontal: 20, borderRadius: 28, padding: 22, marginBottom: 18,
    borderWidth: 1, borderColor: "#FF9AAA", shadowColor: "#FF4D6D",
    shadowOpacity: 0.2, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6,
  },
  heroBadge: {
    flexDirection: "row", alignItems: "center", alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.72)", borderRadius: 20,
    borderWidth: 1, borderColor: "rgba(255,255,255,0.9)",
    paddingHorizontal: 12, paddingVertical: 7, marginBottom: 16,
  },
  heroBadgeText: { fontSize: 12, color: "#6C2D45", fontWeight: "600", marginLeft: 6 },
  heroTitle: { fontSize: 28, fontWeight: "800", color: "#3F1D2F", lineHeight: 34, marginBottom: 12 },
  heroSubtitle: { fontSize: 13, color: "#7A4A5C", lineHeight: 20, marginBottom: 18 },
  bookMoreButton: {
    flexDirection: "row", alignItems: "center", alignSelf: "flex-start",
    backgroundColor: "#FF4D6D", borderRadius: 14, paddingHorizontal: 18, paddingVertical: 12,
  },
  bookMoreButtonText: { fontSize: 14, fontWeight: "700", color: "#FFFFFF", marginRight: 8 },
  statsGrid: {
    flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between",
    marginHorizontal: 20, marginBottom: 8,
  },
  statCard: {
    width: "48%", backgroundColor: "rgba(255,255,255,0.94)", borderRadius: 22,
    padding: 15, marginBottom: 12, borderWidth: 1, borderColor: "#FFB3BF", ...shadow,
  },
  statCardTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
  statIconCircle: { width: 38, height: 38, borderRadius: 14, justifyContent: "center", alignItems: "center" },
  liveBadge: { backgroundColor: "#FFE6EB", borderRadius: 10, paddingHorizontal: 8, paddingVertical: 3 },
  liveBadgeText: { fontSize: 10, color: "#FF4D6D", fontWeight: "700" },
  statLabel: { fontSize: 12, color: "#8D6171", marginTop: 10 },
  statValue: { fontSize: 24, fontWeight: "800", color: "#3F1D2F", marginTop: 2 },
  statSublabel: { fontSize: 11, color: "#8D6171", marginTop: 2 },
  filterTabsRow: { marginHorizontal: 20, marginBottom: 16, flexGrow: 0 },
  filterTab: {
    flexDirection: "row", alignItems: "center", backgroundColor: "#FFFEF7",
    borderRadius: 20, paddingHorizontal: 14, paddingVertical: 9, marginRight: 10,
    borderWidth: 1, borderColor: "#FFB3BF",
  },
  filterTabActive: { backgroundColor: "#FF4D6D", borderColor: "#FF4D6D" },
  filterTabText: { fontSize: 13, fontWeight: "600", color: "#6C2D45" },
  filterTabTextActive: { color: "#FFFFFF" },
  filterTabCount: {
    backgroundColor: "#FFE6EB", borderRadius: 10, paddingHorizontal: 7, paddingVertical: 2, marginLeft: 8,
  },
  filterTabCountActive: { backgroundColor: "rgba(255,255,255,0.25)" },
  filterTabCountText: { fontSize: 11, fontWeight: "700", color: "#FF4D6D" },
  filterTabCountTextActive: { color: "#FFFFFF" },
  sectionCard: {
    backgroundColor: "rgba(255,255,255,0.94)", marginHorizontal: 20, borderRadius: 22,
    padding: 16, marginBottom: 16, borderWidth: 1, borderColor: "#FFB3BF", ...shadow,
  },
  sectionTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
  sectionTitle: { fontSize: 18, fontWeight: "800", color: "#3F1D2F" },
  sectionSubtitle: { fontSize: 12, color: "#8D6171", marginTop: 3, maxWidth: 215 },
  sortPill: {
    flexDirection: "row", alignItems: "center", backgroundColor: "#FFE6EB",
    borderRadius: 20, paddingHorizontal: 10, paddingVertical: 8,
  },
  sortPillText: { fontSize: 11, color: "#6C2D45", marginHorizontal: 3 },
  emptyState: { alignItems: "center", paddingVertical: 40 },
  emptyStateText: { fontSize: 15, fontWeight: "700", color: "#3F1D2F", marginTop: 12 },
  emptyStateSubtext: { fontSize: 12, color: "#8D6171", marginTop: 4, textAlign: "center" },
  errorCard: {
    marginHorizontal: 20, padding: 24, borderRadius: 22, borderWidth: 1,
    borderColor: "#FFB3BF", backgroundColor: "#FFFEF7", alignItems: "center",
  },
  errorText: { color: "#6C2D45", fontSize: 13, textAlign: "center", marginTop: 8 },
  retryButton: { marginTop: 14, borderRadius: 12, backgroundColor: "#FF4D6D", paddingHorizontal: 18, paddingVertical: 10 },
  retryText: { color: "#FFFFFF", fontWeight: "700" },
  loadingCard: { marginHorizontal: 20, paddingVertical: 42, alignItems: "center" },
  loadingText: { marginTop: 12, color: "#8D6171" },
  bookingCard: {
    backgroundColor: "#FFFEF7", borderRadius: 24, padding: 14, marginBottom: 18,
    borderWidth: 1, borderColor: "#FFB3BF", ...shadow,
  },
  bookingHeroImage: { width: "100%", height: 150, borderRadius: 18, marginBottom: 14 },
  bookingHeaderRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10 },
  bookingHeaderCopy: { flex: 1 },
  bookingMetaGrid: { flexDirection: "row", flexWrap: "wrap", marginTop: 16 },
  bookingMetaRow: { width: "50%", flexDirection: "row", alignItems: "center", gap: 7, marginBottom: 12 },
  bookingMetaText: { flex: 1, color: "#6C2D45", fontSize: 12 },
  paymentBox: {
    flexDirection: "row", gap: 6, padding: 12, borderRadius: 16,
    borderWidth: 1, borderColor: "#FFCAD3", backgroundColor: "#FFF5F7",
  },
  paymentColumn: { flex: 1 },
  paymentLabel: { color: "#8D6171", fontSize: 9, marginBottom: 4 },
  paymentValue: { color: "#3F1D2F", fontWeight: "700", fontSize: 12 },
  remainingValue: { color: "#E63B5F", fontWeight: "700", fontSize: 12 },
  payButton: {
    flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8,
    marginTop: 14, paddingVertical: 12, borderRadius: 14, backgroundColor: "#FF4D6D",
  },
  payButtonDisabled: { backgroundColor: "#FFE6EB" },
  payButtonText: { color: "#FFFFFF", fontSize: 13, fontWeight: "700" },
  payButtonTextDisabled: { color: "#8D6171" },
  viewDetailsButton: {
    flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8,
    alignSelf: "flex-start", marginTop: 14, paddingHorizontal: 16, paddingVertical: 11,
    borderRadius: 14, backgroundColor: "#FF4D6D",
  },
  viewDetailsText: { color: "#FFFFFF", fontSize: 13, fontWeight: "700" },
  bookingItem: {
    flexDirection: "row", alignItems: "center", backgroundColor: "#FFFEF7",
    borderRadius: 16, padding: 12, marginBottom: 12, borderWidth: 1, borderColor: "#FFB3BF",
  },
  reviewButton: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "center",
  gap: 6,
  backgroundColor: "#7E22CE",
  paddingVertical: 12,
  borderRadius: 10,
  marginBottom: 10,
},
reviewButtonText: { color: "#FFFFFF", fontWeight: "600", fontSize: 14 },
pendingReviewBadge: {
  flexDirection: "row",
  alignItems: "center",
  gap: 6,
  backgroundColor: "#F3E8FF",
  paddingVertical: 8,
  paddingHorizontal: 10,
  borderRadius: 8,
  marginBottom: 10,
},
pendingReviewText: { color: "#7E22CE", fontSize: 12, fontWeight: "500" },
  bookingItemImage: { width: 56, height: 56, borderRadius: 12 },
  bookingItemVendor: { fontSize: 15, fontWeight: "800", color: "#3F1D2F" },
  bookingItemCategory: { fontSize: 11, color: "#8D6171", marginTop: 2 },
  bookingItemDateRow: { flexDirection: "row", alignItems: "center", marginTop: 4 },
  bookingItemDate: { fontSize: 11, color: "#8D6171", marginLeft: 4 },
  statusPill: { borderRadius: 10, paddingHorizontal: 10, paddingVertical: 5 },
  statusPillText: { fontSize: 11, fontWeight: "700" },
});
