import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#FAFAFA" },
  scrollContent: { paddingBottom: 100 },

  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 16,
    marginBottom: 4,
  },
  backButton: {
    width: 40, height: 40, borderRadius: 20, backgroundColor: "#fff",
    justifyContent: "center", alignItems: "center", elevation: 1, marginRight: 12,
  },
  headerTitle: { fontSize: 20, fontWeight: "700", color: "#333" },

  heroCard: {
    backgroundColor: "#1EA672",
    marginHorizontal: 20,
    marginTop: 16,
    marginBottom: 20,
    borderRadius: 24,
    padding: 20,
  },
  heroBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 5,
    marginBottom: 14,
  },
  heroBadgeText: { color: "#fff", fontSize: 12, fontWeight: "600", marginLeft: 6 },
  heroTitle: { color: "#fff", fontSize: 24, fontWeight: "800", lineHeight: 30 },
  heroSubtitle: { color: "rgba(255,255,255,0.85)", fontSize: 12, marginTop: 10, lineHeight: 18 },

  heroOverviewCard: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 16,
    padding: 16,
    marginTop: 18,
  },
  heroOverviewHeader: { flexDirection: "row", justifyContent: "space-between", marginBottom: 12 },
  heroOverviewTitle: { color: "#fff", fontSize: 14, fontWeight: "700" },
  heroOverviewRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 8 },
  heroOverviewLabel: { color: "rgba(255,255,255,0.8)", fontSize: 12 },
  heroOverviewValue: { color: "#fff", fontSize: 13, fontWeight: "700" },
  heroProgressTrack: {
    height: 6, backgroundColor: "rgba(255,255,255,0.25)", borderRadius: 3, marginTop: 6,
  },
  heroProgressFill: { height: 6, backgroundColor: "#fff", borderRadius: 3 },

  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginHorizontal: 20,
    marginBottom: 8,
  },
  statCard: {
    width: "48%",
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 14,
    marginBottom: 14,
    elevation: 1,
  },
  statTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  statIconCircle: {
    width: 34, height: 34, borderRadius: 17, justifyContent: "center", alignItems: "center",
  },
  liveBadge: { backgroundColor: "#E8F8F0", borderRadius: 10, paddingHorizontal: 8, paddingVertical: 2 },
  liveBadgeText: { fontSize: 10, color: "#22B07D", fontWeight: "700" },
  statLabel: { fontSize: 12, color: "#999", marginTop: 10 },
  statValue: { fontSize: 20, fontWeight: "800", color: "#222", marginTop: 2 },
  statSublabel: { fontSize: 11, color: "#bbb", marginTop: 2 },

  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: 20,
    marginBottom: 4,
  },
  sectionTitle: { fontSize: 16, fontWeight: "700", color: "#333" },
  sectionSubtitle: { fontSize: 12, color: "#999", marginTop: 2, marginBottom: 14, marginHorizontal: 20 },

  managerCard: {
    backgroundColor: "#fff",
    marginHorizontal: 20,
    borderRadius: 18,
    padding: 18,
    marginBottom: 20,
    elevation: 1,
  },
  managerTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  managerTitleRow: { flexDirection: "row", alignItems: "center" },
  managerTitle: { fontSize: 15, fontWeight: "700", color: "#333", marginLeft: 8 },
  managerSubtitle: { fontSize: 12, color: "#999", marginTop: 4 },
  addExpenseButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#22B07D",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  addExpenseButtonText: { color: "#fff", fontWeight: "700", fontSize: 12, marginLeft: 4 },

  expenseCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 12,
    marginHorizontal: 20,
    marginBottom: 10,
    elevation: 1,
  },
  expenseIconCircle: {
    width: 36, height: 36, borderRadius: 18, backgroundColor: "#E8F8F0",
    justifyContent: "center", alignItems: "center",
  },
  expenseTitle: { fontSize: 14, fontWeight: "700", color: "#333" },
  expenseMeta: { fontSize: 11, color: "#999", marginTop: 2 },
  expenseNote: { fontSize: 11, color: "#bbb", marginTop: 2, fontStyle: "italic" },
  expenseAmount: { fontSize: 14, fontWeight: "700", color: "#C2185B", marginBottom: 4 },

  emptyBox: {
    borderWidth: 1,
    borderColor: "#eee",
    borderStyle: "dashed",
    borderRadius: 12,
    paddingVertical: 30,
    alignItems: "center",
    marginHorizontal: 20,
    marginBottom: 20,
    backgroundColor: "#fff",
  },
  emptyBoxText: { color: "#999", fontSize: 13 },

  categoryCard: {
    backgroundColor: "#fff",
    marginHorizontal: 20,
    borderRadius: 18,
    padding: 18,
    marginBottom: 20,
    elevation: 1,
  },
  categoryRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 10 },
  categoryRowLabel: { fontSize: 13, color: "#333", fontWeight: "500" },
  categoryRowValue: { fontSize: 13, color: "#C2185B", fontWeight: "700" },
  categoryBarTrack: { height: 6, backgroundColor: "#f0f0f0", borderRadius: 3, marginBottom: 14 },
  categoryBarFill: { height: 6, backgroundColor: "#C2185B", borderRadius: 3 },

  insightsCard: {
    backgroundColor: "#fff",
    marginHorizontal: 20,
    borderRadius: 18,
    padding: 18,
    marginBottom: 20,
    elevation: 1,
  },
  insightItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    borderRadius: 14,
    padding: 14,
    marginTop: 10,
  },
  insightLabel: { fontSize: 12, fontWeight: "700", color: "#333" },
  insightValue: { fontSize: 12, color: "#555", marginTop: 2 },

  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.4)", justifyContent: "flex-end" },
  addExpenseSheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: "85%",
  },
  addExpenseHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
  addExpenseTitle: { fontSize: 18, fontWeight: "700", color: "#333" },
  fieldLabel: { fontSize: 13, fontWeight: "600", color: "#333", marginBottom: 6, marginTop: 14 },
  fieldInput: {
    borderWidth: 1,
    borderColor: "#eee",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: "#333",
  },
  categoryDropdown: {
    borderWidth: 1,
    borderColor: "#eee",
    borderRadius: 12,
    marginTop: 6,
    overflow: "hidden",
  },
  categoryDropdownItem: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f5f5f5",
  },
  addExpenseFooter: { flexDirection: "row", marginTop: 20, gap: 10 },
  cancelButton: {
    flex: 1, borderWidth: 1, borderColor: "#ddd", borderRadius: 12,
    paddingVertical: 13, alignItems: "center",
  },
  cancelButtonText: { color: "#333", fontWeight: "600" },
  submitButton: {
    flex: 1, backgroundColor: "#C2185B", borderRadius: 12,
    paddingVertical: 13, alignItems: "center",
  },
  submitButtonText: { color: "#fff", fontWeight: "700" },
});