import { StyleSheet } from "react-native";

const shadow = {
  shadowColor: "#FF4D6D",
  shadowOpacity: 0.07,
  shadowRadius: 10,
  shadowOffset: { width: 0, height: 4 },
  elevation: 2,
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#FFF5F7" },
  scrollContent: { paddingBottom: 100 },
  header: { flexDirection: "row", alignItems: "center", paddingHorizontal: 20, paddingTop: 16, marginBottom: 4 },
  backButton: {
    width: 40, height: 40, borderRadius: 14, backgroundColor: "#FFFEF7",
    justifyContent: "center", alignItems: "center", borderWidth: 1, borderColor: "#FFB3BF", marginRight: 12,
  },
  headerTitle: { fontSize: 22, fontWeight: "800", color: "#3F1D2F" },
  heroCard: {
    marginHorizontal: 20, marginTop: 16, marginBottom: 20, borderRadius: 28, padding: 22,
    borderWidth: 1, borderColor: "#FF9AAA", shadowColor: "#FF4D6D",
    shadowOpacity: 0.2, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6,
  },
  heroBadge: {
    flexDirection: "row", alignItems: "center", alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.72)", borderRadius: 20,
    borderWidth: 1, borderColor: "rgba(255,255,255,0.9)",
    paddingHorizontal: 12, paddingVertical: 7, marginBottom: 14,
  },
  heroBadgeText: { color: "#6C2D45", fontSize: 12, fontWeight: "600", marginLeft: 6 },
  heroTitle: { color: "#3F1D2F", fontSize: 28, fontWeight: "800", lineHeight: 34 },
  heroSubtitle: { color: "#7A4A5C", fontSize: 13, marginTop: 10, lineHeight: 20 },
  heroOverviewCard: {
    backgroundColor: "rgba(255,255,255,0.76)", borderRadius: 18, padding: 16, marginTop: 18,
    borderWidth: 1, borderColor: "rgba(255,255,255,0.9)",
  },
  heroOverviewHeader: { flexDirection: "row", justifyContent: "space-between", marginBottom: 12 },
  heroOverviewTitle: { color: "#3F1D2F", fontSize: 14, fontWeight: "800" },
  heroOverviewRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 8 },
  heroOverviewLabel: { color: "#8D6171", fontSize: 12 },
  heroOverviewValue: { color: "#3F1D2F", fontSize: 13, fontWeight: "700" },
  heroProgressTrack: { height: 7, backgroundColor: "#FFE6EB", borderRadius: 4, marginTop: 6 },
  heroProgressFill: { height: 7, backgroundColor: "#FF4D6D", borderRadius: 4 },
  statsGrid: {
    flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between",
    marginHorizontal: 20, marginBottom: 8,
  },
  statCard: {
    width: "48%", backgroundColor: "rgba(255,255,255,0.94)", borderRadius: 22,
    padding: 15, marginBottom: 14, borderWidth: 1, borderColor: "#FFB3BF", ...shadow,
  },
  statTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  statIconCircle: { width: 38, height: 38, borderRadius: 14, justifyContent: "center", alignItems: "center" },
  liveBadge: { backgroundColor: "#FFE6EB", borderRadius: 10, paddingHorizontal: 8, paddingVertical: 3 },
  liveBadgeText: { fontSize: 10, color: "#FF4D6D", fontWeight: "700" },
  statLabel: { fontSize: 12, color: "#8D6171", marginTop: 10 },
  statValue: { fontSize: 20, fontWeight: "800", color: "#3F1D2F", marginTop: 2 },
  statSublabel: { fontSize: 11, color: "#8D6171", marginTop: 2 },
  sectionHeader: {
    flexDirection: "row", justifyContent: "space-between", alignItems: "center",
    marginHorizontal: 20, marginBottom: 4,
  },
  sectionTitle: { fontSize: 18, fontWeight: "800", color: "#3F1D2F" },
  sectionSubtitle: { fontSize: 12, color: "#8D6171", marginTop: 3, marginBottom: 14, marginHorizontal: 20 },
  managerCard: {
    backgroundColor: "rgba(255,255,255,0.94)", marginHorizontal: 20, borderRadius: 22,
    padding: 18, marginBottom: 20, borderWidth: 1, borderColor: "#FFB3BF", ...shadow,
  },
  managerTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  managerTitleRow: { flexDirection: "row", alignItems: "center" },
  managerTitle: { fontSize: 15, fontWeight: "800", color: "#3F1D2F", marginLeft: 8 },
  managerSubtitle: { fontSize: 11, color: "#8D6171", marginTop: 4, maxWidth: 180 },
  addExpenseButton: {
    flexDirection: "row", alignItems: "center", backgroundColor: "#FF4D6D",
    borderRadius: 14, paddingHorizontal: 12, paddingVertical: 10,
  },
  addExpenseButtonText: { color: "#FFFFFF", fontWeight: "700", fontSize: 11, marginLeft: 4 },
  expenseCard: {
    flexDirection: "row", alignItems: "center", backgroundColor: "#FFFEF7",
    borderRadius: 18, padding: 13, marginHorizontal: 20, marginBottom: 10,
    borderWidth: 1, borderColor: "#FFB3BF", ...shadow,
  },
  expenseIconCircle: {
    width: 38, height: 38, borderRadius: 14, backgroundColor: "#FFE6EB",
    justifyContent: "center", alignItems: "center",
  },
  expenseTitle: { fontSize: 14, fontWeight: "800", color: "#3F1D2F" },
  expenseMeta: { fontSize: 11, color: "#8D6171", marginTop: 2 },
  expenseNote: { fontSize: 11, color: "#B8919F", marginTop: 2, fontStyle: "italic" },
  expenseAmount: { fontSize: 14, fontWeight: "700", color: "#FF4D6D", marginBottom: 4 },
  emptyBox: {
    borderWidth: 1, borderColor: "#FFCAD3", borderStyle: "dashed", borderRadius: 16,
    paddingVertical: 30, alignItems: "center", marginHorizontal: 20, marginBottom: 20,
    backgroundColor: "#FFFEF7",
  },
  emptyBoxText: { color: "#8D6171", fontSize: 13 },
  categoryCard: {
    backgroundColor: "rgba(255,255,255,0.94)", marginHorizontal: 20, borderRadius: 22,
    padding: 18, marginBottom: 20, borderWidth: 1, borderColor: "#FFB3BF", ...shadow,
  },
  categoryRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 10 },
  categoryRowLabel: { fontSize: 13, color: "#3F1D2F", fontWeight: "600" },
  categoryRowValue: { fontSize: 13, color: "#FF4D6D", fontWeight: "700" },
  categoryBarTrack: { height: 7, backgroundColor: "#FFE6EB", borderRadius: 4, marginBottom: 14 },
  categoryBarFill: { height: 7, backgroundColor: "#FF4D6D", borderRadius: 4 },
  insightsCard: {
    backgroundColor: "rgba(255,255,255,0.94)", marginHorizontal: 20, borderRadius: 22,
    padding: 18, marginBottom: 20, borderWidth: 1, borderColor: "#FFB3BF", ...shadow,
  },
  insightItem: { flexDirection: "row", alignItems: "flex-start", borderRadius: 14, padding: 14, marginTop: 10 },
  insightLabel: { fontSize: 12, fontWeight: "700", color: "#3F1D2F" },
  insightValue: { fontSize: 12, color: "#6C2D45", marginTop: 2 },
  modalOverlay: { flex: 1, backgroundColor: "rgba(63,29,47,0.45)", justifyContent: "flex-end" },
  addExpenseSheet: {
    backgroundColor: "#FFFEF7", borderTopLeftRadius: 26, borderTopRightRadius: 26,
    padding: 20, maxHeight: "85%", borderWidth: 1, borderColor: "#FFB3BF",
  },
  addExpenseHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
  addExpenseTitle: { fontSize: 19, fontWeight: "800", color: "#3F1D2F" },
  fieldLabel: { fontSize: 13, fontWeight: "600", color: "#3F1D2F", marginBottom: 6, marginTop: 14 },
  fieldInput: {
    borderWidth: 1, borderColor: "#FFB3BF", borderRadius: 14,
    paddingHorizontal: 14, paddingVertical: 12, fontSize: 14, color: "#3F1D2F", backgroundColor: "#FFFFFF",
  },
  categoryDropdown: { borderWidth: 1, borderColor: "#FFB3BF", borderRadius: 14, marginTop: 6, overflow: "hidden" },
  categoryDropdownItem: { paddingHorizontal: 14, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: "#FFCAD3" },
  addExpenseFooter: { flexDirection: "row", marginTop: 20, gap: 10 },
  cancelButton: {
    flex: 1, borderWidth: 1, borderColor: "#FFB3BF", borderRadius: 14,
    paddingVertical: 13, alignItems: "center", backgroundColor: "#FFFEF7",
  },
  cancelButtonText: { color: "#6C2D45", fontWeight: "700" },
  submitButton: { flex: 1, backgroundColor: "#FF4D6D", borderRadius: 14, paddingVertical: 13, alignItems: "center" },
  submitButtonText: { color: "#FFFFFF", fontWeight: "700" },
});
