import { StyleSheet } from "react-native";

const shadow = {
  shadowColor: "#6c2d45",
  shadowOpacity: 0.08,
  shadowRadius: 10,
  shadowOffset: { width: 0, height: 4 },
  elevation: 2,
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#fffef7" },
  keyboardView: { flex: 1 },
  header: {
    minHeight: 72,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#f3cad5",
    backgroundColor: "rgba(255,254,247,0.98)",
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#f1d9df",
    marginRight: 10,
    ...shadow,
  },
  headerAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  headerAvatarText: { color: "#fff", fontSize: 17, lineHeight: 22, fontWeight: "800" },
  headerCopy: { flex: 1, minWidth: 0 },
  headerTitle: {
    fontSize: 17,
    lineHeight: 23,
    fontWeight: "800",
    color: "#3f1d2f",
    paddingRight: 4,
  },
  headerSubtitle: { fontSize: 11, lineHeight: 16, color: "#956477", paddingRight: 4 },

  connectionBar: {
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  connectedBar: { backgroundColor: "#effbf3", borderBottomColor: "#cdebd7" },
  disconnectedBar: { backgroundColor: "#fff7ed", borderBottomColor: "#fed7aa" },
  connectionDot: { width: 8, height: 8, borderRadius: 4, marginRight: 7 },
  connectedDot: { backgroundColor: "#22a95b" },
  disconnectedDot: { backgroundColor: "#f97316" },
  connectionText: { fontSize: 11, lineHeight: 16, color: "#287a49", fontWeight: "700", paddingRight: 4 },
  disconnectedText: { color: "#9a3412" },

  warningBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginHorizontal: 12,
    marginTop: 10,
    marginBottom: 2,
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#fdba74",
    backgroundColor: "#fff7ed",
    ...shadow,
  },
  warningIconBox: {
    width: 34,
    height: 34,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffedd5",
    flexShrink: 0,
  },
  warningCopy: { flex: 1, minWidth: 0, marginLeft: 10 },
  warningTitle: { fontSize: 12, lineHeight: 18, fontWeight: "800", color: "#9a3412", paddingRight: 4 },
  warningText: { fontSize: 11, lineHeight: 16, color: "#9a3412", marginTop: 1, paddingRight: 4 },
  warningClose: { padding: 5, marginTop: -3, marginRight: -3 },

  chatBackground: { flex: 1, overflow: "hidden" },
  decorations: { ...StyleSheet.absoluteFillObject, overflow: "hidden" },
  flowerTop: { position: "absolute", right: -22, top: 36, transform: [{ rotate: "-18deg" }] },
  heartCenter: { position: "absolute", left: 30, top: "42%", transform: [{ rotate: "-12deg" }] },
  sparkleBottom: { position: "absolute", right: 34, bottom: 70, transform: [{ rotate: "12deg" }] },
  decorativeRingOne: {
    position: "absolute",
    width: 190,
    height: 190,
    borderRadius: 95,
    borderWidth: 24,
    borderColor: "rgba(255,143,161,0.035)",
    left: -115,
    top: 70,
  },
  decorativeRingTwo: {
    position: "absolute",
    width: 250,
    height: 250,
    borderRadius: 125,
    borderWidth: 34,
    borderColor: "rgba(201,24,91,0.028)",
    right: -155,
    bottom: -55,
  },

  messageList: { paddingHorizontal: 16, paddingTop: 18, paddingBottom: 22, flexGrow: 1 },
  emptyMessageList: { justifyContent: "center" },
  messageBubble: {
    maxWidth: "82%",
    minWidth: 74,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 7,
    marginBottom: 10,
    ...shadow,
  },
  userBubble: {
    backgroundColor: "#c9185b",
    alignSelf: "flex-end",
    borderBottomRightRadius: 6,
  },
  vendorBubble: {
    backgroundColor: "rgba(255,255,255,0.96)",
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "#f3dbe2",
    borderBottomLeftRadius: 6,
  },
  messageText: { fontSize: 14, lineHeight: 20, color: "#3f1d2f", paddingRight: 3 },
  userMessageText: { color: "#fff" },
  messageTime: { fontSize: 10, lineHeight: 14, color: "#9c7280", marginTop: 3, alignSelf: "flex-end", paddingRight: 2 },
  userMessageTime: { color: "rgba(255,255,255,0.76)" },

  chatEmptyState: { alignItems: "center", paddingHorizontal: 30 },
  chatEmptyIcon: {
    width: 62,
    height: 62,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.9)",
    borderWidth: 1,
    borderColor: "#f2cbd6",
    marginBottom: 12,
    ...shadow,
  },
  chatEmptyTitle: { fontSize: 16, lineHeight: 23, fontWeight: "800", color: "#3f1d2f", paddingRight: 4 },
  chatEmptyText: { fontSize: 12, lineHeight: 19, color: "#8d6171", textAlign: "center", marginTop: 5, paddingHorizontal: 4 },

  inputRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#f0d4dc",
    backgroundColor: "#fffef7",
  },
  inputShell: {
    flex: 1,
    minHeight: 46,
    maxHeight: 110,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff5f7",
    borderRadius: 23,
    borderWidth: 1,
    borderColor: "#f1cbd5",
    paddingLeft: 14,
    marginRight: 9,
  },
  input: {
    flex: 1,
    minHeight: 44,
    maxHeight: 106,
    paddingHorizontal: 10,
    paddingTop: 11,
    paddingBottom: 10,
    fontSize: 14,
    lineHeight: 20,
    color: "#3f1d2f",
  },
  sendButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#c9185b",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#c9185b",
    shadowOpacity: 0.24,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  sendButtonDisabled: { backgroundColor: "#d9a6b7", shadowOpacity: 0.08, elevation: 1 },

  emptyState: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: "#fff5f7" },
  emptyStateText: { fontSize: 14, lineHeight: 20, color: "#8d6171", paddingRight: 4 },
});
