import { StyleSheet } from "react-native";

const cardShadow = {
  shadowColor: "#6c2d45",
  shadowOpacity: 0.07,
  shadowRadius: 12,
  shadowOffset: { width: 0, height: 5 },
  elevation: 2,
};

const safeText = {
  paddingRight: 4,
  flexShrink: 1,
} as const;

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#fffef7" },
  scrollContent: { paddingTop: 10, paddingBottom: 110, backgroundColor: "#fff5f7" },

  heroCard: {
    position: "relative",
    overflow: "hidden",
    marginHorizontal: 20,
    borderRadius: 28,
    padding: 22,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#ff9aaa",
    shadowColor: "#ff4d6d",
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  heroDecorations: { ...StyleSheet.absoluteFillObject, overflow: "hidden" },
  heroRingOne: {
    position: "absolute",
    width: 210,
    height: 210,
    borderRadius: 105,
    borderWidth: 26,
    borderColor: "rgba(255,255,255,0.08)",
    right: -120,
    top: -80,
  },
  heroRingTwo: {
    position: "absolute",
    width: 150,
    height: 150,
    borderRadius: 75,
    borderWidth: 18,
    borderColor: "rgba(108,45,69,0.04)",
    left: -85,
    bottom: 48,
  },
  heroSparkle: { position: "absolute", right: 22, top: 120, transform: [{ rotate: "12deg" }] },
  heroBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.24)",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.45)",
  },
  heroBadgeText: { fontSize: 12, lineHeight: 17, color: "#fff", fontWeight: "700", marginLeft: 6, ...safeText },
  heroTitle: { fontSize: 29, lineHeight: 37, fontWeight: "800", color: "#3f1d2f", marginBottom: 12, ...safeText },
  heroSubtitle: { fontSize: 13, color: "#5f3043", lineHeight: 20, marginBottom: 18, fontWeight: "500", ...safeText },
  addTaskButton: {
    alignSelf: "flex-start",
    backgroundColor: "#fffef7",
    borderRadius: 14,
    paddingHorizontal: 17,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.85)",
    ...cardShadow,
  },
  addTaskButtonText: { fontSize: 14, lineHeight: 20, fontWeight: "800", color: "#ff4d6d", ...safeText },
  heroSummaryCard: {
    marginTop: 20,
    borderRadius: 20,
    padding: 15,
    backgroundColor: "rgba(255,248,216,0.92)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.72)",
  },
  heroSummaryHeader: { flexDirection: "row", alignItems: "center", marginBottom: 11 },
  heroSummaryTitle: { marginLeft: 7, fontSize: 14, lineHeight: 20, fontWeight: "800", color: "#3f1d2f", ...safeText },
  heroSummaryGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between" },
  heroSummaryItem: { width: "48%", minWidth: 0, marginBottom: 10 },
  heroSummaryLabel: { fontSize: 10, lineHeight: 15, color: "#8d6171", ...safeText },
  heroSummaryValue: { fontSize: 12, lineHeight: 18, fontWeight: "800", color: "#3f1d2f", marginTop: 2, ...safeText },

  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginHorizontal: 20,
    marginBottom: 8,
  },
  statCard: {
    width: "48%",
    minWidth: 0,
    backgroundColor: "#fffdf0",
    borderRadius: 22,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#ffb3bf",
    ...cardShadow,
  },
  statCardTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
  statIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: "#ffe6eb",
    justifyContent: "center",
    alignItems: "center",
  },
  liveBadge: { backgroundColor: "#fff8d8", borderRadius: 999, paddingHorizontal: 8, paddingVertical: 4 },
  liveBadgeText: { fontSize: 10, lineHeight: 14, color: "#6c2d45", fontWeight: "700", ...safeText },
  statLabel: { fontSize: 12, lineHeight: 18, color: "#8d6171", marginTop: 12, ...safeText },
  statValue: { fontSize: 25, lineHeight: 33, fontWeight: "800", color: "#3f1d2f", marginTop: 2, ...safeText },
  statSublabel: { fontSize: 11, lineHeight: 17, color: "#8d6171", marginTop: 1, ...safeText },

  sectionCard: {
    backgroundColor: "rgba(255,255,255,0.96)",
    marginHorizontal: 20,
    borderRadius: 24,
    padding: 17,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: "#ffb3bf",
    ...cardShadow,
  },
  sectionTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
  sectionHeadingCopy: { flex: 1, minWidth: 0, marginRight: 8 },
  sectionTitle: { fontSize: 18, lineHeight: 25, fontWeight: "800", color: "#3f1d2f", ...safeText },
  sectionSubtitle: { fontSize: 12, lineHeight: 18, color: "#8d6171", marginTop: 2, ...safeText },
  countPill: { backgroundColor: "#fff8d8", borderRadius: 999, paddingHorizontal: 11, paddingVertical: 7, flexShrink: 0 },
  countPillText: { fontSize: 10, lineHeight: 15, color: "#6c2d45", fontWeight: "700", paddingRight: 2 },

  emptyBox: {
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#ffb3bf",
    borderRadius: 16,
    paddingVertical: 32,
    paddingHorizontal: 18,
    alignItems: "center",
    marginTop: 14,
    backgroundColor: "#fffaf4",
  },
  emptyBoxText: { fontSize: 13, lineHeight: 19, color: "#8d6171", textAlign: "center", paddingHorizontal: 4 },

  taskCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#fffefb",
    borderRadius: 18,
    paddingVertical: 8,
    paddingHorizontal: 5,
    marginBottom: 11,
    borderWidth: 1,
    borderColor: "#f5d5dd",
  },
  taskCardDone: { backgroundColor: "#fff8d8", borderColor: "#f3ddb1" },
  taskCopy: { flex: 1, minWidth: 0, paddingTop: 7 },
  taskText: { fontSize: 14, lineHeight: 21, fontWeight: "700", color: "#3f1d2f", ...safeText },
  taskTextDone: { textDecorationLine: "line-through", color: "#b1788b" },
  taskDescription: { fontSize: 11, lineHeight: 17, color: "#8d6171", marginTop: 2, ...safeText },
  taskMetaRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", marginTop: 7 },
  priorityPill: { borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3, marginRight: 8, marginBottom: 2 },
  priorityPillText: { fontSize: 10, lineHeight: 14, fontWeight: "700", paddingRight: 2 },
  dueDateRow: { flexDirection: "row", alignItems: "center", marginBottom: 2 },
  dueDateText: { fontSize: 10, lineHeight: 15, color: "#8d6171", marginLeft: 3, paddingRight: 3 },
  taskActions: { flexDirection: "row", flexShrink: 0, paddingTop: 2 },
  taskActionButton: { margin: 0, width: 34, height: 34, borderWidth: 1, borderColor: "#ffb3bf", backgroundColor: "#fff" },
  taskDeleteButton: { margin: 0, marginLeft: 2, width: 34, height: 34, borderWidth: 1, borderColor: "#ffd0d8", backgroundColor: "#fff5f7" },

  timelineRow: { flexDirection: "row", alignItems: "stretch", minHeight: 92 },
  timelineRail: { width: 34, alignItems: "center" },
  timelineDot: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#ffe6eb",
    borderWidth: 1,
    borderColor: "#ffb3bf",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
  },
  timelineDotDone: { backgroundColor: "#ff4d6d", borderColor: "#ff4d6d" },
  timelineLine: { width: 2, flex: 1, backgroundColor: "#ffe6eb", marginVertical: 3 },
  timelineContent: {
    flex: 1,
    minWidth: 0,
    marginLeft: 9,
    marginBottom: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#fff3b0",
    padding: 12,
    backgroundColor: "#fffefb",
  },
  timelineTask: { fontSize: 13, lineHeight: 19, fontWeight: "700", color: "#3f1d2f", ...safeText },
  timelineDescription: { fontSize: 11, lineHeight: 17, color: "#8d6171", marginTop: 2, ...safeText },
  timelineDate: { fontSize: 10, lineHeight: 15, color: "#8d6171", marginTop: 5, ...safeText },
  timelineStatus: { alignSelf: "flex-start", marginTop: 7, borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3, backgroundColor: "#ffe6eb" },
  timelineStatusDone: { backgroundColor: "#fff8d8" },
  timelineStatusText: { fontSize: 9, lineHeight: 13, fontWeight: "700", color: "#ff4d6d", paddingRight: 2 },
  timelineStatusTextDone: { color: "#6c2d45" },

  previewRow: { flexDirection: "row", justifyContent: "space-between", marginHorizontal: 20, marginBottom: 16 },
  previewCard: {
    width: "48%",
    minWidth: 0,
    backgroundColor: "#fffdf0",
    borderRadius: 22,
    padding: 14,
    borderWidth: 1,
    borderColor: "#ffb3bf",
    ...cardShadow,
  },
  previewCardHeader: { flexDirection: "row", alignItems: "center", marginBottom: 12, minWidth: 0 },
  previewIconCircle: { width: 32, height: 32, borderRadius: 13, justifyContent: "center", alignItems: "center", marginRight: 7, flexShrink: 0 },
  previewCardTitle: { fontSize: 12, lineHeight: 18, fontWeight: "800", color: "#3f1d2f", ...safeText },
  previewStatRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 5 },
  previewStatLabel: { fontSize: 10, lineHeight: 15, color: "#8d6171", ...safeText },
  previewStatValue: { fontSize: 11, lineHeight: 16, fontWeight: "800", color: "#3f1d2f", textAlign: "right", ...safeText },
  previewFootnote: { fontSize: 9, lineHeight: 14, color: "#8d6171", marginTop: 7, ...safeText },
  previewBigValue: { fontSize: 14, lineHeight: 21, fontWeight: "800", color: "#3f1d2f", marginTop: 2, ...safeText },
  previewVendorRow: { flexDirection: "row", alignItems: "center", marginBottom: 6 },
  previewVendorText: { fontSize: 10, lineHeight: 15, color: "#6c2d45", marginLeft: 6, ...safeText },
  progressBarTrack: { height: 7, backgroundColor: "#fff8d8", borderRadius: 4, marginTop: 9, overflow: "hidden" },
  progressBarFill: { height: 7, borderRadius: 4 },

  modalOverlay: { flex: 1, backgroundColor: "rgba(63,29,47,0.48)", justifyContent: "center", padding: 18 },
  modalCard: { backgroundColor: "#fffef7", borderRadius: 24, padding: 18, borderWidth: 1, borderColor: "#ffb3bf", ...cardShadow },
  modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 18 },
  modalTitleRow: { flexDirection: "row", alignItems: "center", flex: 1, minWidth: 0 },
  modalTitleIcon: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#ffe6eb", marginRight: 9 },
  modalTitleCopy: { flex: 1, minWidth: 0 },
  modalTitle: { fontSize: 17, lineHeight: 23, fontWeight: "800", color: "#3f1d2f", ...safeText },
  modalSubtitle: { fontSize: 10, lineHeight: 15, color: "#8d6171", ...safeText },
  modalInput: { marginBottom: 12, backgroundColor: "#fffef7" },
  modalTextArea: { minHeight: 82 },
  modalRow: { marginBottom: 12 },
  priorityPicker: { flexDirection: "row", justifyContent: "space-between" },
  priorityChip: { flex: 1, borderWidth: 1, borderColor: "#ffb3bf", borderRadius: 11, paddingVertical: 9, alignItems: "center", marginRight: 7, backgroundColor: "#fff" },
  priorityChipActive: { backgroundColor: "#ff4d6d", borderColor: "#ff4d6d" },
  priorityChipText: { fontSize: 12, lineHeight: 17, color: "#6c2d45", fontWeight: "700", paddingRight: 3 },
  priorityChipTextActive: { color: "#fff" },
  modalButtonRow: { flexDirection: "row", justifyContent: "flex-end", marginTop: 8 },
  modalCancelButton: { marginRight: 9, borderColor: "#ffb3bf" },
  modalAddButton: { backgroundColor: "#ff4d6d" },
});
