import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#FAFAFA",
  },
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 16,
    paddingBottom: 100,
  },

  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  headerLeft: { flexDirection: "row", alignItems: "flex-start" },
  headerRight: { flexDirection: "row", alignItems: "center" },
  greeting: { fontSize: 16, color: "#333" },
  subGreeting: { fontSize: 12, color: "#999", marginTop: 2 },
  bellButton: { marginRight: 12, position: "relative" },
  badge: {
    position: "absolute",
    top: -2,
    right: -2,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#C2185B",
  },
  avatar: { width: 40, height: 40, borderRadius: 20 },
  avatarPlaceholder: {
  justifyContent: "center",
  alignItems: "center",
},

  weddingCard: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 20,
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
  },
  weddingIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
  },
  weddingLabel: { fontSize: 12, color: "#C2185B", fontWeight: "600" },
  weddingDate: { fontSize: 18, fontWeight: "700", color: "#333", marginTop: 2 },
  daysLeft: { fontSize: 12, color: "#C2185B", fontWeight: "600", marginTop: 2 },
  weddingImage: { width: 50, height: 50, borderRadius: 12 },

  budgetPill: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#fff",
    marginHorizontal: 20,
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
    elevation: 1,
  },
  budgetPillLeft: { flexDirection: "row", alignItems: "center" },
  budgetPillLabel: { marginLeft: 8, fontSize: 14, color: "#333", fontWeight: "500" },
  budgetPillRight: { flexDirection: "row", alignItems: "center" },
  budgetPillValue: { fontSize: 14, fontWeight: "700", color: "#333", marginRight: 4 },

  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 20,
    marginBottom: 20,
  },
  searchInputWrapper: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 14,
    paddingHorizontal: 14,
    height: 46,
    elevation: 1,
  },
  searchInput: { flex: 1, marginLeft: 8, fontSize: 14, color: "#333" },
  filterButton: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 10,
    elevation: 1,
  },

  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: 20,
    marginBottom: 12,
  },
  sectionTitle: { fontSize: 16, fontWeight: "700", color: "#333" },
  viewAll: { fontSize: 13, color: "#C2185B", fontWeight: "600" },

  categoriesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginHorizontal: 20,
    marginBottom: 20,
  },
  categoryItem: {
    width: "23%",
    aspectRatio: 1,
    backgroundColor: "#fff",
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    elevation: 1,
  },
  categoryText: { marginTop: 8, fontSize: 11, fontWeight: "600", color: "#333" },

  vendorCard: {
    width: 220,
    backgroundColor: "#fff",
    borderRadius: 20,
    overflow: "hidden",
    marginRight: 15,
    elevation: 1,
  },
  vendorImage: { width: "100%", height: 130 },
  vendorHeart: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "#fff",
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  vendorTitle: { fontSize: 15, fontWeight: "700", color: "#333" },
  vendorRatingRow: { flexDirection: "row", alignItems: "center", marginTop: 4 },
  vendorRating: { fontSize: 12, marginLeft: 4, color: "#333", fontWeight: "600" },
  vendorCategory: { fontSize: 12, color: "#999", marginLeft: 4 },
  vendorPrice: { fontSize: 12, color: "#C2185B", fontWeight: "600", marginTop: 6 },

  rowCards: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 20,
    marginBottom: 20,
  },
  progressCard: {
    width: "48%",
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 14,
    elevation: 1,
  },
  progressHeader: { flexDirection: "row", alignItems: "center", marginBottom: 8 },
  progressTitle: { fontSize: 12, fontWeight: "600", color: "#333", marginLeft: 6 },
  progressBig: { fontSize: 16, fontWeight: "700", color: "#333" },
  progressSmall: { fontSize: 11, color: "#999", fontWeight: "400" },
  progressBarTrack: {
    height: 6,
    backgroundColor: "#EEE",
    borderRadius: 3,
    marginTop: 10,
    marginBottom: 6,
  },
  progressBarFill: { height: 6, borderRadius: 3 },
  progressPercent: { fontSize: 11, color: "#999" },

  bookingCard: {
    flexDirection: "row",
    backgroundColor: "#FFF8E1",
    marginHorizontal: 20,
    borderRadius: 18,
    padding: 14,
    marginBottom: 20,
    alignItems: "center",
  },
  bookingLabel: { fontSize: 11, color: "#B8860B", fontWeight: "600" },
  bookingTitle: { fontSize: 14, fontWeight: "700", color: "#333", marginTop: 4 },
  bookingTime: { fontSize: 12, color: "#777", marginTop: 4 },
  bookingImage: { width: 60, height: 50, borderRadius: 10, marginLeft: 10 },

  notificationItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#fff",
    marginHorizontal: 20,
    borderRadius: 14,
    padding: 14,
    elevation: 1,
  },
  notifText: { fontSize: 13, color: "#333", flexShrink: 1 },
  notifTime: { fontSize: 11, color: "#999", marginTop: 4 },
  heroButtonRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 16,
  },
  heroButtonPrimary: {
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginRight: 10,
    marginBottom: 8,
  },
  heroButtonPrimaryText: { color: "#C2185B", fontWeight: "700", fontSize: 13 },
  heroButtonSecondary: {
    backgroundColor: "rgba(255,255,255,0.25)",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginRight: 10,
    marginBottom: 8,
  },
  heroButtonSecondaryText: { color: "#fff", fontWeight: "700", fontSize: 13 },

  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginHorizontal: 20,
    marginBottom: 8,
  },

  quickActionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginHorizontal: 20,
    marginBottom: 8,
  },

  activityCard: {
    backgroundColor: "#fff",
    marginHorizontal: 20,
    borderRadius: 18,
    padding: 18,
    marginBottom: 20,
    elevation: 1,
  },
  activityEmptyBox: {
    borderWidth: 1,
    borderColor: "#eee",
    borderStyle: "dashed",
    borderRadius: 12,
    paddingVertical: 30,
    alignItems: "center",
    marginTop: 12,
  },
  activityEmptyText: { color: "#999", fontSize: 13 },

  weddingProgressCard: {
    backgroundColor: "#fff",
    marginHorizontal: 20,
    borderRadius: 18,
    padding: 18,
    marginBottom: 20,
    elevation: 1,
  },
  weddingProgressTitle: { fontSize: 16, fontWeight: "700", color: "#333" },
  weddingProgressSubtitle: { fontSize: 12, color: "#999", marginTop: 2, marginBottom: 14 },
  weddingProgressTopRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 6 },
  weddingProgressLabel: { fontSize: 12, color: "#999" },
  weddingProgressPercent: { fontSize: 13, fontWeight: "700", color: "#C2185B" },
  weddingProgressItem: { flexDirection: "row", alignItems: "center", paddingVertical: 9 },
  weddingProgressItemText: { marginLeft: 12, fontSize: 14, color: "#333" },
  weddingProgressItemDone: { textDecorationLine: "line-through", color: "#aaa" },
});