import { StyleSheet } from "react-native";

const cardShadow = {
  shadowColor: "#ff4d6d",
  shadowOpacity: 0.07,
  shadowRadius: 10,
  shadowOffset: { width: 0, height: 4 },
  elevation: 2,
};

const textSafe = {
  paddingRight: 4,
  flexShrink: 1,
} as const;

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#fffef7" },
  container: { flex: 1, backgroundColor: "#fff5f7" },
  scrollContent: { paddingTop: 16, paddingBottom: 110 },

  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  headerLeft: { flexDirection: "row", alignItems: "flex-start", flex: 1, minWidth: 0 },
  headerCopy: { marginLeft: 12, flex: 1, minWidth: 0 },
  headerRight: { flexDirection: "row", alignItems: "center", flexShrink: 0 },
  greeting: { fontSize: 20, lineHeight: 27, fontWeight: "800", color: "#3f1d2f", ...textSafe },
  subGreeting: { fontSize: 12, lineHeight: 18, color: "#8d6171", marginTop: 1, ...textSafe },
  headerName: { color: "#6c2d45", fontWeight: "700" },
  bellButton: {
    width: 38,
    height: 38,
    borderRadius: 13,
    marginRight: 10,
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffe6eb",
  },
  badge: {
    position: "absolute",
    top: 3,
    right: 2,
    minWidth: 16,
    height: 16,
    paddingHorizontal: 3,
    borderRadius: 8,
    backgroundColor: "#ff4d6d",
    borderWidth: 1,
    borderColor: "#fffef7",
    alignItems: "center",
    justifyContent: "center",
  },
  badgeText: { color: "#fff", fontSize: 8, lineHeight: 10, fontWeight: "800" },
  avatar: { width: 40, height: 40, borderRadius: 20 },
  avatarPlaceholder: { justifyContent: "center", alignItems: "center" },
  avatarCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ff4d6d",
    borderWidth: 2,
    borderColor: "#fffef7",
  },
  avatarInitial: { color: "#fff", fontSize: 16, fontWeight: "800" },

  weddingCard: {
    alignItems: "flex-start",
    marginHorizontal: 20,
    borderRadius: 28,
    padding: 22,
    marginBottom: 22,
    borderWidth: 1,
    borderColor: "#ff9aaa",
    shadowColor: "#ff4d6d",
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  weddingIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
  },
  weddingLabel: { fontSize: 12, color: "#6c2d45", fontWeight: "600" },
  heroGreetingPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.75)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.9)",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  heroGreetingText: { marginLeft: 6, fontSize: 12, fontWeight: "600", color: "#6c2d45" },
  weddingDate: { fontSize: 29, lineHeight: 38, fontWeight: "800", color: "#3f1d2f", marginTop: 16, ...textSafe },
  heroDescription: { color: "#7a4a5c", fontSize: 13, lineHeight: 20, marginTop: 12, ...textSafe },
  heroTagRow: { flexDirection: "row", flexWrap: "wrap", marginTop: 14 },
  heroTag: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.9)",
    backgroundColor: "rgba(255,255,255,0.72)",
    paddingHorizontal: 11,
    paddingVertical: 7,
    marginRight: 7,
    marginBottom: 7,
  },
  heroTagText: { color: "#6c2d45", fontSize: 11, fontWeight: "700" },
  daysLeft: { fontSize: 12, color: "#ff4d6d", fontWeight: "600", marginTop: 2 },
  weddingImage: { width: 50, height: 50, borderRadius: 12 },
  heroButtonRow: { flexDirection: "row", flexWrap: "wrap", marginTop: 12 },
  heroButtonPrimary: {
    backgroundColor: "#ff4d6d",
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginRight: 8,
    marginBottom: 8,
  },
  heroButtonPrimaryText: { color: "#fff", fontWeight: "700", fontSize: 13 },
  heroButtonSecondary: {
    backgroundColor: "rgba(255,255,255,0.72)",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginRight: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.9)",
  },
  heroButtonSecondaryText: { color: "#6c2d45", fontWeight: "700", fontSize: 12 },

  budgetPill: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#fffef7",
    marginHorizontal: 20,
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#ffb3bf",
  },
  budgetPillLeft: { flexDirection: "row", alignItems: "center" },
  budgetPillLabel: { marginLeft: 8, fontSize: 14, color: "#3f1d2f", fontWeight: "500" },
  budgetPillRight: { flexDirection: "row", alignItems: "center" },
  budgetPillValue: { fontSize: 14, fontWeight: "700", color: "#3f1d2f", marginRight: 4 },

  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginHorizontal: 20,
    marginBottom: 10,
  },
  quickActionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginHorizontal: 20,
    marginBottom: 10,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: 20,
    marginBottom: 12,
  },
  sectionTitle: { fontSize: 20, lineHeight: 28, fontWeight: "800", color: "#3f1d2f", ...textSafe },
  sectionSubtitle: { fontSize: 12, color: "#8d6171", marginTop: 3, maxWidth: 300 },
  viewAll: { fontSize: 13, color: "#ff4d6d", fontWeight: "700" },

  activityCard: {
    backgroundColor: "rgba(255,255,255,0.94)",
    marginHorizontal: 20,
    borderRadius: 24,
    padding: 18,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#ffb3bf",
    ...cardShadow,
  },
  cardSubtitle: { fontSize: 12, color: "#8d6171" },
  activityEmptyBox: {
    borderWidth: 1,
    borderColor: "#ffcad3",
    borderStyle: "dashed",
    borderRadius: 14,
    paddingVertical: 30,
    alignItems: "center",
    marginTop: 12,
    backgroundColor: "#fff5f7",
  },
  activityEmptyText: { color: "#8d6171", fontSize: 13 },
  activityList: { marginTop: 10 },
  activityRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#ffcad3",
  },
  activityIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffe6eb",
    flexShrink: 0,
  },
  activityCopy: { flex: 1, minWidth: 0, marginHorizontal: 10 },
  activityTitle: { fontSize: 13, lineHeight: 19, fontWeight: "700", color: "#3f1d2f", ...textSafe },
  activityDetail: { fontSize: 11, lineHeight: 17, color: "#8d6171", textTransform: "capitalize", ...textSafe },
  activityDate: { fontSize: 10, color: "#8d6171", flexShrink: 0, paddingRight: 2 },

  weddingProgressCard: {
    backgroundColor: "rgba(255,255,255,0.94)",
    marginHorizontal: 20,
    borderRadius: 24,
    padding: 18,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#ffb3bf",
    ...cardShadow,
  },
  weddingProgressTitle: { fontSize: 20, lineHeight: 28, fontWeight: "800", color: "#3f1d2f", ...textSafe },
  weddingProgressSubtitle: { fontSize: 12, lineHeight: 18, color: "#8d6171", marginTop: 1, marginBottom: 14, ...textSafe },
  weddingProgressTopRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 6 },
  weddingProgressLabel: { fontSize: 12, lineHeight: 18, color: "#8d6171", ...textSafe },
  weddingProgressPercent: { fontSize: 13, lineHeight: 19, fontWeight: "700", color: "#ff4d6d", paddingHorizontal: 3 },
  weddingProgressItem: { flexDirection: "row", alignItems: "center", paddingVertical: 9 },
  weddingProgressItemText: { marginLeft: 12, fontSize: 14, lineHeight: 21, color: "#3f1d2f", ...textSafe },
  weddingProgressItemDone: { textDecorationLine: "line-through", color: "#b8919f" },
  progressBarTrack: {
    height: 7,
    backgroundColor: "#ffe6eb",
    borderRadius: 4,
    marginTop: 10,
    marginBottom: 6,
  },
  progressBarFill: { height: 7, borderRadius: 4 },
  progressPercent: { fontSize: 11, color: "#8d6171" },

  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 20,
    marginBottom: 22,
  },
  searchInputWrapper: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.94)",
    borderRadius: 16,
    paddingHorizontal: 14,
    height: 48,
    borderWidth: 1,
    borderColor: "#ffb3bf",
  },
  searchInput: { flex: 1, marginLeft: 8, fontSize: 14, color: "#3f1d2f" },
  filterButton: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: "#ffe6eb",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 10,
    borderWidth: 1,
    borderColor: "#ffb3bf",
  },

  categoriesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginHorizontal: 20,
    marginBottom: 20,
  },
  categoryItem: {
    width: "23%",
    aspectRatio: 1,
    backgroundColor: "rgba(255,255,255,0.94)",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#ffb3bf",
  },
  categoryText: { marginTop: 8, fontSize: 11, lineHeight: 16, fontWeight: "700", color: "#3f1d2f", paddingHorizontal: 3, textAlign: "center" },

  vendorCard: {
    width: 220,
    backgroundColor: "rgba(255,255,255,0.96)",
    borderRadius: 22,
    overflow: "hidden",
    marginRight: 15,
    borderWidth: 1,
    borderColor: "#ffb3bf",
    ...cardShadow,
  },
  vendorImage: { width: "100%", height: 130 },
  vendorHeart: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "#fffef7",
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  vendorTitle: { fontSize: 15, fontWeight: "800", color: "#3f1d2f" },
  vendorRatingRow: { flexDirection: "row", alignItems: "center", marginTop: 4 },
  vendorRating: { fontSize: 12, marginLeft: 4, color: "#3f1d2f", fontWeight: "600" },
  vendorCategory: { fontSize: 12, color: "#8d6171", marginLeft: 4 },
  vendorPrice: { fontSize: 12, color: "#ff4d6d", fontWeight: "700", marginTop: 6 },

  rowCards: { flexDirection: "row", justifyContent: "space-between", marginHorizontal: 20, marginBottom: 20 },
  progressCard: { width: "48%", backgroundColor: "#fff", borderRadius: 18, padding: 14, ...cardShadow },
  progressHeader: { flexDirection: "row", alignItems: "center", marginBottom: 8 },
  progressTitle: { fontSize: 12, fontWeight: "600", color: "#3f1d2f", marginLeft: 6 },
  progressBig: { fontSize: 16, fontWeight: "700", color: "#3f1d2f" },
  progressSmall: { fontSize: 11, color: "#8d6171", fontWeight: "400" },

  bookingCard: {
    flexDirection: "row",
    backgroundColor: "#fffef7",
    marginHorizontal: 20,
    borderRadius: 22,
    padding: 16,
    marginBottom: 20,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ffb3bf",
  },
  bookingCopy: { flex: 1, minWidth: 0 },
  bookingLabel: { fontSize: 11, color: "#ff4d6d", fontWeight: "700" },
  bookingTitle: { fontSize: 14, lineHeight: 20, fontWeight: "800", color: "#3f1d2f", marginTop: 4, ...textSafe },
  bookingTime: { fontSize: 12, lineHeight: 18, color: "#8d6171", marginTop: 4, ...textSafe },
  bookingEmptyText: { fontSize: 13, lineHeight: 20, color: "#8d6171", marginTop: 6, ...textSafe },
  bookingIconBox: {
    width: 54,
    height: 54,
    borderRadius: 16,
    marginLeft: 10,
    backgroundColor: "#ffe6eb",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  featuredList: { paddingLeft: 20, paddingRight: 5, paddingBottom: 10 },
  sectionEmptyBox: {
    marginHorizontal: 20,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: "#ffcad3",
    borderStyle: "dashed",
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    backgroundColor: "#fffef7",
  },

  notificationItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#fff",
    marginHorizontal: 20,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "#ffb3bf",
  },
  notifText: { fontSize: 13, color: "#3f1d2f", flexShrink: 1 },
  notifTime: { fontSize: 11, color: "#8d6171", marginTop: 4 },
});
