import { StyleSheet } from "react-native";

const shadow = {
  shadowColor: "#FF4D6D",
  shadowOpacity: 0.07,
  shadowRadius: 10,
  shadowOffset: { width: 0, height: 4 },
  elevation: 2,
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#FFF5F7" },
  scrollContent: { paddingTop: 10, paddingBottom: 40 },

  heroCard: {
  marginHorizontal: 20,
  borderRadius: 28,
  padding: 22,
  marginBottom: 18,
  backgroundColor: "#FFE1E8", // ADDED — solid tint, fixes the floating white patch bug
  borderWidth: 1,
  borderColor: "#FF9AAA",
  shadowColor: "#FF4D6D",
  shadowOpacity: 0.2,
  shadowRadius: 16,
  shadowOffset: { width: 0, height: 8 },
  elevation: 6,
},
  heroBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.72)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.9)",
    paddingHorizontal: 12,
    paddingVertical: 7,
    marginBottom: 16,
  },
  heroBadgeText: { fontSize: 12, color: "#6C2D45", fontWeight: "600", marginLeft: 6 },
  heroTitle: { fontSize: 20, fontWeight: "800", color: "#3F1D2F", lineHeight: 26, marginBottom: 6 },
  heroSubtitle: { fontSize: 13, color: "#7A4A5C", lineHeight: 20 },

  newRequestButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginHorizontal: 20,
    marginBottom: 20,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: "#FF4D6D",
  },
  newRequestButtonText: { color: "#FFFFFF", fontSize: 14, fontWeight: "700" },

  requestCard: {
    backgroundColor: "rgba(255,255,255,0.94)",
    marginHorizontal: 20,
    borderRadius: 22,
    padding: 16,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: "#FFB3BF",
    ...shadow,
  },
  requestTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
  requestDate: { fontSize: 12, color: "#8D6171" },
  requestTitle: { fontSize: 17, fontWeight: "800", color: "#3F1D2F", marginTop: 4 },
  requestMeta: { fontSize: 12, color: "#8D6171", marginTop: 2 },

  statusPill: { borderRadius: 10, paddingHorizontal: 10, paddingVertical: 5 },
  statusPillText: { fontSize: 11, fontWeight: "700" },

  stepperRow: { flexDirection: "row", flexWrap: "wrap", marginTop: 14, marginBottom: 4 },
  stepPill: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 6,
    marginBottom: 6,
    borderWidth: 1,
  },
  stepPillDone: { backgroundColor: "#FFE6EB", borderColor: "#FF4D6D" },
  stepPillPending: { backgroundColor: "#FFFEF7", borderColor: "#FFB3BF" },
  stepPillTextDone: { fontSize: 11, fontWeight: "700", color: "#FF4D6D", marginLeft: 4 },
  stepPillTextPending: { fontSize: 11, fontWeight: "600", color: "#8D6171", marginLeft: 4 },

  sectionDivider: { height: 1, backgroundColor: "#FFE6EB", marginVertical: 14 },

  vendorCard: {
    backgroundColor: "#FFFEF7",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#FFB3BF",
    padding: 12,
    marginBottom: 10,
  },
  vendorCardTitle: { fontSize: 14, fontWeight: "700", color: "#3F1D2F" },
  vendorCardSubtitle: { fontSize: 11, color: "#8D6171", marginTop: 2 },
  vendorViewButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    alignSelf: "flex-start",
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: "#FFE6EB",
  },
  vendorViewButtonText: { color: "#FF4D6D", fontSize: 12, fontWeight: "700" },

  quotationBox: {
    flexDirection: "row",
    gap: 6,
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#FFCAD3",
    backgroundColor: "#FFF5F7",
    marginTop: 4,
  },
  quotationColumn: { flex: 1 },
  quotationLabel: { color: "#8D6171", fontSize: 10, marginBottom: 4 },
  quotationValue: { color: "#3F1D2F", fontWeight: "800", fontSize: 20 },

  responseRow: { flexDirection: "row", gap: 10, marginTop: 14 },
  acceptButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: "#FF4D6D",
  },
  acceptButtonText: { color: "#FFFFFF", fontWeight: "700", fontSize: 13 },
  rejectButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#FFB3BF",
    backgroundColor: "#FFFEF7",
  },
  rejectButtonText: { color: "#6C2D45", fontWeight: "700", fontSize: 13 },

  emptyState: { alignItems: "center", paddingVertical: 40, paddingHorizontal: 30 },
  emptyStateText: { fontSize: 15, fontWeight: "700", color: "#3F1D2F", marginTop: 12, textAlign: "center" },
  emptyStateSubtext: { fontSize: 12, color: "#8D6171", marginTop: 6, textAlign: "center" },

  loadingCard: { marginHorizontal: 20, paddingVertical: 42, alignItems: "center" },
  loadingText: { marginTop: 12, color: "#8D6171" },

  errorCard: {
    marginHorizontal: 20,
    padding: 24,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#FFB3BF",
    backgroundColor: "#FFFEF7",
    alignItems: "center",
  },
  errorText: { color: "#6C2D45", fontSize: 13, textAlign: "center", marginTop: 8 },
  retryButton: { marginTop: 14, borderRadius: 12, backgroundColor: "#FF4D6D", paddingHorizontal: 18, paddingVertical: 10 },
  retryText: { color: "#FFFFFF", fontWeight: "700" },

  upgradeCard: {
    marginHorizontal: 20,
    marginBottom: 20,
    padding: 26,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#FFB3BF",
    backgroundColor: "rgba(255,255,255,0.94)",
    alignItems: "center",
  },
  upgradeTitle: { fontSize: 16, fontWeight: "800", color: "#3F1D2F", marginTop: 12, textAlign: "center" },
  upgradeSubtext: { fontSize: 12, color: "#8D6171", marginTop: 8, textAlign: "center", lineHeight: 18 },
  upgradeButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 18,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: "#FF4D6D",
  },
  upgradeButtonText: { color: "#FFFFFF", fontSize: 13, fontWeight: "700" },

  // Form styles
  formCard: {
    backgroundColor: "rgba(255,255,255,0.94)",
    marginHorizontal: 20,
    borderRadius: 22,
    padding: 18,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: "#FFB3BF",
    ...shadow,
  },
  fieldLabel: { fontSize: 13, fontWeight: "700", color: "#3F1D2F", marginBottom: 6, marginTop: 14 },
  input: {
    backgroundColor: "#FFFEF7",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#FFB3BF",
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: "#3F1D2F",
  },
  inputMultiline: { minHeight: 90, textAlignVertical: "top" },
  chipsRow: {
  flexDirection: "row",
  flexWrap: "wrap",
  marginTop: 4,
  gap: 8, // ADDED — cleaner, consistent spacing than relying only on marginRight/marginBottom
},
chip: {
  borderRadius: 20,
  paddingHorizontal: 14,
  paddingVertical: 9,
  minHeight: 36, // ADDED — keeps every chip the same height regardless of text length
  marginBottom: 8,
  borderWidth: 1.5, // was 1 — slightly bolder outline for definition
  borderColor: "#FFB3BF",
  backgroundColor: "#FFF0F3", // CHANGED from #FFFEF7 — soft pink tint, now visibly distinct from the card's near-white background
  alignItems: "center",
  justifyContent: "center",
},
chipSelected: {
  backgroundColor: "#FF4D6D",
  borderColor: "#FF4D6D",
  shadowColor: "#FF4D6D", // ADDED — subtle glow so selected chips pop
  shadowOpacity: 0.3,
  shadowRadius: 6,
  shadowOffset: { width: 0, height: 3 },
  elevation: 3,
},
chipText: {
  fontSize: 12,
  fontWeight: "700", // was 600 — slightly bolder, reads better on the tinted fill
  color: "#6C2D45",
},
chipTextSelected: { color: "#FFFFFF" },
  submitButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 24,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: "#FF4D6D",
  },
  headerBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 6,
    paddingBottom: 14,
  },
  headerBackButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(255,255,255,0.9)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#FFB3BF",
    marginRight: 12,
  },
  headerTitle: {
    fontSize: 19,
    fontWeight: "800",
    color: "#3F1D2F",
  },
  quotationCard: {
    backgroundColor: "#FFFEF7",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#FFCAD3",
    padding: 16,
    marginTop: 4,
  },
  quotationHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  quotationHeaderText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#3F1D2F",
  },
  quotationTotalRow: {
    marginTop: 10,
    marginBottom: 14,
  },
  quotationTotalLabel: {
    fontSize: 11,
    color: "#8D6171",
    marginBottom: 4,
  },
  quotationTotalValue: {
    fontSize: 28,
    fontWeight: "800",
    color: "#3F1D2F",
  },
  quotationBreakdownDivider: {
    height: 1,
    backgroundColor: "#FFE6EB",
    marginBottom: 10,
  },
  quotationLineRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
  },
  quotationLineLabel: {
    fontSize: 13,
    color: "#6C2D45",
    flex: 1,
  },
  quotationLineValue: {
    fontSize: 13,
    fontWeight: "700",
    color: "#3F1D2F",
  },
  quotationNotesBox: {
    marginTop: 12,
    padding: 12,
    borderRadius: 14,
    backgroundColor: "#FFF5F7",
    borderWidth: 1,
    borderColor: "#FFE6EB",
  },
  quotationNotesLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: "#8D6171",
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  quotationNotesText: {
    fontSize: 12,
    color: "#6C2D45",
    lineHeight: 18,
  },
  advanceDueBox: {
    marginTop: 4,
    marginBottom: 14,
    padding: 12,
    borderRadius: 14,
    backgroundColor: "#FFF9E6",
    borderWidth: 1,
    borderColor: "#F5D97A",
    alignSelf: "flex-start",
  },
  advanceDueLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: "#8A6D1E",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  advanceDueValue: {
    fontSize: 18,
    fontWeight: "800",
    color: "#3F1D2F",
  },

  quotationSectionLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#8D6171",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  quotationLineSubLabel: {
    fontSize: 11,
    color: "#B98A96",
    marginTop: 2,
  },

  payAdvanceButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 14,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: "#FF4D6D",
  },
  payAdvanceButtonText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 13,
  },

  bookedConfirmationCard: {
    marginTop: 14,
    padding: 16,
    borderRadius: 18,
    backgroundColor: "#DCFCE7",
    borderWidth: 1,
    borderColor: "#86E6A8",
  },
  bookedConfirmationHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  },
  bookedConfirmationTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#15803D",
  },
  bookedConfirmationSubtext: {
    fontSize: 12,
    color: "#3F6B4C",
    lineHeight: 18,
  },
  goToBookingsButton: {
    marginTop: 14,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 13,
    borderRadius: 14,
    backgroundColor: "#15803D",
  },
  goToBookingsButtonText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 13,
  },
  submitButtonDisabled: { backgroundColor: "#FFB3BF" },
  submitButtonText: { color: "#FFFFFF", fontSize: 14, fontWeight: "700" },
  fieldError: { color: "#E63B5F", fontSize: 11, marginTop: 4 },
});