import { StyleSheet } from "react-native";

const palette = {
  background: "#fff5f7",
  surface: "#fffef7",
  surfaceSoft: "#fff9fa",
  plum: "#3f1d2f",
  plumSoft: "#6c2d45",
  muted: "#8d6171",
  coral: "#ff4d6d",
  coralDark: "#d4145a",
  blush: "#ff8fa1",
  border: "#ffb3bf",
  borderSoft: "#ffe0e6",
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.background,
  },
  scrollContent: {
    paddingBottom: 110,
  },

  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 8,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.borderSoft,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    shadowColor: palette.plum,
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  headerTitle: {
    flexShrink: 1,
    paddingRight: 2,
    fontSize: 22,
    lineHeight: 29,
    fontWeight: "800",
    color: palette.plum,
  },

  heroCard: {
    position: "relative",
    overflow: "hidden",
    marginHorizontal: 20,
    marginTop: 14,
    marginBottom: 20,
    borderRadius: 26,
    padding: 21,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.55)",
    shadowColor: palette.coralDark,
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 7 },
    elevation: 5,
  },
  heroDecorations: {
    ...StyleSheet.absoluteFillObject,
  },
  heroRingLarge: {
    position: "absolute",
    width: 170,
    height: 170,
    borderRadius: 85,
    borderWidth: 28,
    borderColor: "rgba(255,255,255,0.12)",
    right: -55,
    top: -45,
  },
  heroRingSmall: {
    position: "absolute",
    width: 74,
    height: 74,
    borderRadius: 37,
    borderWidth: 15,
    borderColor: "rgba(255,255,255,0.12)",
    left: -24,
    bottom: 38,
  },
  heroWatermark: {
    position: "absolute",
    right: 20,
    bottom: 16,
  },
  heroBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.22)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginBottom: 14,
  },
  heroBadgeText: {
    color: "#fff",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
    marginLeft: 6,
    paddingRight: 1,
  },
  heroTitle: {
    color: "#fff",
    fontSize: 25,
    fontWeight: "800",
    lineHeight: 32,
    paddingRight: 2,
  },
  heroSubtitle: {
    maxWidth: "92%",
    color: "rgba(255,255,255,0.92)",
    fontSize: 13,
    marginTop: 10,
    lineHeight: 20,
    paddingRight: 2,
  },
  heroStatusBox: {
    backgroundColor: "rgba(255,254,247,0.88)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.7)",
    borderRadius: 17,
    paddingHorizontal: 13,
    paddingTop: 12,
    paddingBottom: 4,
    marginTop: 18,
  },
  heroStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  heroStatusIcon: {
    width: 29,
    height: 29,
    borderRadius: 15,
    backgroundColor: "#ffe8ed",
    justifyContent: "center",
    alignItems: "center",
  },
  heroStatusText: {
    flexShrink: 1,
    color: palette.plum,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
    marginLeft: 10,
    paddingRight: 2,
  },

  card: {
    backgroundColor: palette.surface,
    marginHorizontal: 20,
    borderRadius: 20,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: palette.border,
    shadowColor: palette.plum,
    shadowOpacity: 0.07,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  cardHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  cardHeaderTitle: {
    flexShrink: 1,
    paddingRight: 2,
    fontSize: 17,
    lineHeight: 23,
    fontWeight: "800",
    color: palette.plum,
  },
  editButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: palette.coral,
    borderRadius: 12,
    paddingHorizontal: 13,
    paddingVertical: 8,
    marginLeft: 10,
  },
  editButtonText: {
    color: "#fff",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    marginLeft: 4,
    paddingRight: 1,
  },

  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
  },
  infoIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#ffe8ed",
    borderWidth: 1,
    borderColor: palette.borderSoft,
    justifyContent: "center",
    alignItems: "center",
  },
  infoCopy: {
    flex: 1,
    minWidth: 0,
    marginLeft: 12,
  },
  infoLabel: {
    color: palette.muted,
    fontSize: 11,
    lineHeight: 16,
    paddingRight: 2,
  },
  infoValue: {
    flexShrink: 1,
    color: palette.plum,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
    marginTop: 1,
    paddingRight: 3,
  },

  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 56,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: palette.borderSoft,
  },
  toggleCopy: {
    flex: 1,
    minWidth: 0,
    marginRight: 12,
  },
  toggleLabel: {
    flexShrink: 1,
    color: palette.plumSoft,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
    paddingRight: 2,
  },
  toggleDescription: {
    flexShrink: 1,
    color: palette.muted,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 2,
    paddingRight: 2,
  },

  securityItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: palette.surfaceSoft,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: palette.borderSoft,
    padding: 13,
    marginBottom: 12,
  },
  securityIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#ffe8ed",
    justifyContent: "center",
    alignItems: "center",
  },
  securityCopy: {
    flex: 1,
    minWidth: 0,
    marginLeft: 12,
    marginRight: 8,
  },
  securityTitle: {
    flexShrink: 1,
    color: palette.plum,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "800",
    paddingRight: 2,
  },
  securityDescription: {
    flexShrink: 1,
    color: palette.muted,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 2,
    paddingRight: 2,
  },
  comingSoonText: {
    color: palette.blush,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 2,
    fontStyle: "italic",
    paddingRight: 2,
  },

  dangerCard: {
    backgroundColor: "#fff0f3",
    marginHorizontal: 20,
    borderRadius: 20,
    padding: 18,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: palette.border,
  },
  dangerTitle: {
    color: palette.plum,
    fontSize: 17,
    lineHeight: 23,
    fontWeight: "800",
    paddingRight: 2,
  },
  dangerSubtitle: {
    color: palette.muted,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
    marginBottom: 16,
    paddingRight: 2,
  },
  dangerButtonRow: {
    flexDirection: "row",
    gap: 10,
  },
  logoutButton: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surface,
    borderRadius: 13,
    paddingHorizontal: 8,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: palette.blush,
  },
  logoutButtonText: {
    flexShrink: 1,
    color: palette.plumSoft,
    fontWeight: "800",
    fontSize: 13,
    lineHeight: 18,
    marginLeft: 6,
    paddingRight: 1,
  },
  deleteButton: {
    flex: 1.25,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.coralDark,
    borderRadius: 13,
    paddingHorizontal: 8,
    paddingVertical: 12,
  },
  deleteButtonText: {
    flexShrink: 1,
    color: "#fff",
    fontWeight: "800",
    fontSize: 13,
    lineHeight: 18,
    marginLeft: 6,
    paddingRight: 1,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(63,29,47,0.45)",
    justifyContent: "flex-end",
  },
  editProfileSheet: {
    backgroundColor: palette.surface,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: palette.border,
    padding: 20,
    maxHeight: "88%",
  },
  addExpenseHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  addExpenseTitle: {
    flexShrink: 1,
    color: palette.plum,
    fontSize: 19,
    lineHeight: 26,
    fontWeight: "800",
    paddingRight: 8,
  },
  sectionSubheading: {
    color: palette.coralDark,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
    marginTop: 18,
    marginBottom: 8,
    paddingRight: 2,
  },
  fieldLabel: {
    color: palette.plumSoft,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
    marginBottom: 6,
    marginTop: 10,
    paddingRight: 2,
  },
  fieldInput: {
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 13,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    lineHeight: 20,
    color: palette.plum,
  },
  saveButton: {
    backgroundColor: palette.coral,
    borderRadius: 13,
    paddingVertical: 15,
    alignItems: "center",
    marginTop: 20,
    shadowColor: palette.coralDark,
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  saveButtonText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 15,
    lineHeight: 21,
    paddingRight: 2,
  },
});
