import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#FAFAFA" },
  scrollContent: { paddingBottom: 100 },

  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 16,
    marginBottom: 4,
  },
  backButton: {
    width: 40, height: 40, borderRadius: 20, backgroundColor: "#fff",
    justifyContent: "center", alignItems: "center", elevation: 1, marginRight: 12,
  },
  headerTitle: { fontSize: 20, fontWeight: "700", color: "#333" },

  heroCard: {
    backgroundColor: "#1F2937",
    marginHorizontal: 20,
    marginTop: 16,
    marginBottom: 20,
    borderRadius: 24,
    padding: 20,
  },
  heroBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.15)",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 5,
    marginBottom: 14,
  },
  heroBadgeText: { color: "#fff", fontSize: 12, fontWeight: "600", marginLeft: 6 },
  heroTitle: { color: "#fff", fontSize: 22, fontWeight: "800", lineHeight: 28 },
  heroSubtitle: { color: "rgba(255,255,255,0.75)", fontSize: 12, marginTop: 10, lineHeight: 18 },
  heroStatusBox: {
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: 16,
    padding: 14,
    marginTop: 18,
  },
  heroStatusRow: { flexDirection: "row", alignItems: "center", marginBottom: 8 },
  heroStatusText: { color: "#fff", fontSize: 13, fontWeight: "600", marginLeft: 10 },

  card: {
    backgroundColor: "#fff",
    marginHorizontal: 20,
    borderRadius: 18,
    padding: 18,
    marginBottom: 16,
    elevation: 1,
  },
  cardHeaderRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 14 },
  cardHeaderTitle: { fontSize: 16, fontWeight: "700", color: "#C2185B" },
  editButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1F2937",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  editButtonText: { color: "#fff", fontSize: 12, fontWeight: "700", marginLeft: 4 },

  infoRow: { flexDirection: "row", alignItems: "center", marginBottom: 14 },
  infoIconCircle: {
    width: 34, height: 34, borderRadius: 17, backgroundColor: "#f5f5f5",
    justifyContent: "center", alignItems: "center",
  },
  infoLabel: { fontSize: 11, color: "#999" },
  infoValue: { fontSize: 14, fontWeight: "700", color: "#333", marginTop: 2 },

  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f5f5f5",
  },
  toggleLabel: { fontSize: 14, color: "#333", fontWeight: "500" },
  toggleDescription: { fontSize: 11, color: "#999", marginTop: 2 },

  securityItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#FAFAFA",
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
  },
  securityIconCircle: {
    width: 36, height: 36, borderRadius: 18, backgroundColor: "#eee",
    justifyContent: "center", alignItems: "center",
  },
  securityTitle: { fontSize: 13, fontWeight: "700", color: "#333" },
  securityDescription: { fontSize: 11, color: "#999", marginTop: 2, lineHeight: 15 },
  comingSoonText: { fontSize: 11, color: "#bbb", marginTop: 2, fontStyle: "italic" },

  dangerCard: {
    backgroundColor: "#FDEEEE",
    marginHorizontal: 20,
    borderRadius: 18,
    padding: 18,
    marginBottom: 20,
  },
  dangerTitle: { fontSize: 16, fontWeight: "700", color: "#D32F2F" },
  dangerSubtitle: { fontSize: 12, color: "#B71C1C", marginTop: 4, marginBottom: 16 },
  dangerButtonRow: { flexDirection: "row", gap: 10 },
  logoutButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "#22B07D",
  },
  logoutButtonText: { color: "#22B07D", fontWeight: "700", marginLeft: 6 },
  deleteButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E53935",
    borderRadius: 12,
    paddingVertical: 12,
  },
  deleteButtonText: { color: "#fff", fontWeight: "700", marginLeft: 6 },

  // Edit Profile modal (reuses some Budget modal patterns)
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.4)", justifyContent: "flex-end" },
  editProfileSheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: "88%",
  },
  addExpenseHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 10 },
  addExpenseTitle: { fontSize: 18, fontWeight: "700", color: "#333" },
  sectionSubheading: { fontSize: 13, fontWeight: "700", color: "#C2185B", marginTop: 18, marginBottom: 8 },
  fieldLabel: { fontSize: 12, fontWeight: "600", color: "#666", marginBottom: 6, marginTop: 10 },
  fieldInput: {
    borderWidth: 1,
    borderColor: "#eee",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 14,
    color: "#333",
  },
  saveButton: {
    backgroundColor: "#C2185B",
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: "center",
    marginTop: 20,
  },
  saveButtonText: { color: "#fff", fontWeight: "700", fontSize: 15 },
});