import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FFF5F7" },
  scrollContent: { paddingBottom: 100 },

  heroImage: {
    width: "100%",
    height: 320, // keep your existing height if different
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    overflow: "hidden",
  },
  heroOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 20,
    paddingTop: 60,
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  safeArea: { flex: 1, backgroundColor: "#FFF5F7" },
  backButton: {
    position: "absolute",
    top: 50,
    left: 20,
    width: 40, height: 40, borderRadius: 20,
    backgroundColor: "rgba(255,254,247,0.94)",
    justifyContent: "center", alignItems: "center",
    zIndex: 10,
  },

  badgeRow: { flexDirection: "row", marginBottom: 12 },
  ratingBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
  },
  ratingBadgeText: { fontSize: 12, fontWeight: "700", color: "#3F1D2F", marginLeft: 4 },
  categoryBadge: {
    backgroundColor: "#FF4D6D",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  categoryBadgeText: { fontSize: 12, fontWeight: "700", color: "#fff" },

  vendorName: { fontSize: 26, fontWeight: "800", color: "#fff" },
  locationPriceRow: { flexDirection: "row", alignItems: "center", marginTop: 8 },
  locationText: { fontSize: 13, color: "#fff", marginLeft: 4, marginRight: 14 },
  priceText: { fontSize: 16, fontWeight: "700", color: "#fff" },

  actionRow: { flexDirection: "row", marginTop: 16 },
  saveButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 11,
    marginRight: 10,
  },
  saveButtonText: { fontSize: 13, fontWeight: "700", color: "#3F1D2F", marginLeft: 6 },
  saveButtonTextActive: { color: "#FF4D6D" },
  shareButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 11,
  },
  shareButtonText: { fontSize: 13, fontWeight: "700", color: "#fff", marginLeft: 6 },

  card: {
    backgroundColor: "#FFFEF7",
    marginHorizontal: 20,
    marginTop: 16,
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: "#FFB3BF",
    shadowColor: "#FF4D6D",
    shadowOpacity: 0.07,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  cardTitle: { fontSize: 17, fontWeight: "800", color: "#3F1D2F", marginBottom: 4 },
  cardSubtitle: { fontSize: 12, color: "#8D6171", marginBottom: 14 },

  emptyText: { fontSize: 13, color: "#8D6171", textAlign: "center", paddingVertical: 20 },

  aboutText: { fontSize: 13, color: "#6C2D45", lineHeight: 21 },

  amenitiesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginTop: 16,
  },
  amenityItem: {
    width: "48%",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFE6EB",
    borderWidth: 1,
    borderColor: "#FFCAD3",
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 12,
    marginBottom: 10,
  },
  amenityText: { fontSize: 13, color: "#3F1D2F", fontWeight: "500", marginLeft: 10 },

  reviewSummaryBox: {
    flexDirection: "row",
    backgroundColor: "#FFF5F7",
    borderWidth: 1,
    borderColor: "#FFCAD3",
    borderRadius: 16,
    padding: 18,
    marginTop: 10,
  },
  reviewScoreBig: { fontSize: 32, fontWeight: "800", color: "#3F1D2F" },
  starsRow: { flexDirection: "row", marginTop: 4 },
  reviewCountText: { fontSize: 12, color: "#8D6171", marginTop: 6 },

  ratingBarsColumn: { flex: 1, marginLeft: 20, justifyContent: "center" },
  ratingBarRow: { flexDirection: "row", alignItems: "center", marginBottom: 6 },
  ratingBarLabel: { fontSize: 11, color: "#8D6171", width: 26 },
  ratingBarTrack: { flex: 1, height: 6, backgroundColor: "#FFE6EB", borderRadius: 3, marginHorizontal: 8 },
  ratingBarFill: { height: 6, backgroundColor: "#F5A623", borderRadius: 3 },
  reviewsHeaderRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
  writeReviewButton: { backgroundColor: "#FF4D6D", borderRadius: 12, paddingHorizontal: 14, paddingVertical: 8 },
  writeReviewButtonText: { fontSize: 12, fontWeight: "700", color: "#fff" },
myReviewCard: {
    backgroundColor: "#FFF5F7", borderRadius: 14, padding: 14, marginTop: 14, borderWidth: 1, borderColor: "#FFCAD3",
  },
  myReviewHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 8 },
  myReviewLabel: { fontSize: 12, fontWeight: "700", color: "#FF4D6D" },
  myReviewActions: { flexDirection: "row" },
  myReviewIconButton: { marginLeft: 12 },
  myReviewText: { fontSize: 13, color: "#3F1D2F", marginTop: 4, lineHeight: 19 },

  sendInquiryButton: {
    flexDirection: "row", alignItems: "center", justifyContent: "center",
    borderWidth: 1, borderColor: "#FF4D6D", borderRadius: 14,
    marginHorizontal: 20, marginTop: 16, paddingVertical: 13,
  },
  sendInquiryButtonText: { fontSize: 14, fontWeight: "700", color: "#FF4D6D", marginLeft: 8 },
  bookNowFixed: {
    backgroundColor: "#FF4D6D",
    marginHorizontal: 20,
    marginTop: 20,
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: "center",
  },
  bookNowFixedText: { color: "#fff", fontWeight: "700", fontSize: 15 },
});
