import {
  Building2,
  Camera,
  Video,
  Flower2,
  Sparkles,
  Hand,
  UtensilsCrossed,
  Cake,
  Music2,
  Drum,
  PartyPopper,
  HeartHandshake,
  CarFront,
  Hotel,
  Mail,
  Shirt,
  Gem,
  Flower,
  Landmark,
  WandSparkles,
  Mic2,
  Gift,
  Package,
  Volume2,
  ShieldCheck,
  Baby,
  Boxes,
} from "lucide-react";

export const VENDOR_CATEGORIES = [
  "Venue",
  "Photographer",
  "Videographer",
  "Decorator",
  "Makeup Artist",
  "Mehendi Artist",
  "Caterer",
  "Cake Designer",
  "DJ",
  "Live Band",
  "Entertainment",
  "Wedding Planner",
  "Transportation",
  "Accommodation",
  "Invitation Designer",
  "Bridal Wear",
  "Groom Wear",
  "Jewellery",
  "Florist",
  "Pandit / Priest",
  "Event Planner",
  "Birthday Planner",
  "Kids Party Planner",
  "Balloon Decorator",
  "Theme Decorator",
  "Kids Entertainer",
  "Magician",
  "Anchor / Emcee",
  "Choreographer",
  "Party Supplies",
  "Return Gifts",
  "Gift Hampers",
  "Sound and Lighting",
  "Photo Booth",
  "Event Security",
] as const;

export const CATEGORY_CARDS = [
  {
    id: 1,
    title: "Venue",
    count: "120+ Vendors",
    icon: Building2,
  },
  {
    id: 2,
    title: "Photographer",
    count: "90+ Vendors",
    icon: Camera,
  },
  {
    id: 3,
    title: "Videographer",
    count: "70+ Vendors",
    icon: Video,
  },
  {
    id: 4,
    title: "Decorator",
    count: "80+ Vendors",
    icon: Flower2,
  },
  {
    id: 5,
    title: "Makeup Artist",
    count: "75+ Vendors",
    icon: Sparkles,
  },
  {
    id: 6,
    title: "Mehendi Artist",
    count: "55+ Vendors",
    icon: Hand,
  },
  {
    id: 7,
    title: "Caterer",
    count: "110+ Vendors",
    icon: UtensilsCrossed,
  },
  {
    id: 8,
    title: "Cake Designer",
    count: "45+ Vendors",
    icon: Cake,
  },
  {
    id: 9,
    title: "DJ",
    count: "65+ Vendors",
    icon: Music2,
  },
  {
    id: 10,
    title: "Live Band",
    count: "30+ Vendors",
    icon: Drum,
  },
  {
    id: 11,
    title: "Entertainment",
    count: "40+ Vendors",
    icon: PartyPopper,
  },
  {
    id: 12,
    title: "Wedding Planner",
    count: "60+ Vendors",
    icon: HeartHandshake,
  },
  {
    id: 13,
    title: "Transportation",
    count: "35+ Vendors",
    icon: CarFront,
  },
  {
    id: 14,
    title: "Accommodation",
    count: "25+ Vendors",
    icon: Hotel,
  },
  {
    id: 15,
    title: "Invitation Designer",
    count: "30+ Vendors",
    icon: Mail,
  },
  {
    id: 16,
    title: "Bridal Wear",
    count: "50+ Vendors",
    icon: Shirt,
  },
  {
    id: 17,
    title: "Groom Wear",
    count: "45+ Vendors",
    icon: Shirt,
  },
  {
    id: 18,
    title: "Jewellery",
    count: "55+ Vendors",
    icon: Gem,
  },
  {
    id: 19,
    title: "Florist",
    count: "40+ Vendors",
    icon: Flower,
  },
  {
    id: 20,
    title: "Pandit / Priest",
    count: "20+ Vendors",
    icon: Landmark,
  },
  { id: 21, title: "Event Planner", count: "40+ Vendors", icon: PartyPopper },
  { id: 22, title: "Birthday Planner", count: "30+ Vendors", icon: Cake },
  { id: 23, title: "Kids Party Planner", count: "25+ Vendors", icon: Baby },
  { id: 24, title: "Balloon Decorator", count: "35+ Vendors", icon: Flower2 },
  { id: 25, title: "Theme Decorator", count: "30+ Vendors", icon: Sparkles },
  { id: 26, title: "Kids Entertainer", count: "20+ Vendors", icon: PartyPopper },
  { id: 27, title: "Magician", count: "15+ Vendors", icon: WandSparkles },
  { id: 28, title: "Anchor / Emcee", count: "25+ Vendors", icon: Mic2 },
  { id: 29, title: "Choreographer", count: "30+ Vendors", icon: Music2 },
  { id: 30, title: "Party Supplies", count: "25+ Vendors", icon: Boxes },
  { id: 31, title: "Return Gifts", count: "20+ Vendors", icon: Gift },
  { id: 32, title: "Gift Hampers", count: "25+ Vendors", icon: Package },
  { id: 33, title: "Sound and Lighting", count: "35+ Vendors", icon: Volume2 },
  { id: 34, title: "Photo Booth", count: "20+ Vendors", icon: Camera },
  { id: 35, title: "Event Security", count: "15+ Vendors", icon: ShieldCheck },
];

export const CATEGORY_ICON_MAP = {
  Venue: Building2,
  Photographer: Camera,
  Videographer: Video,
  Decorator: Flower2,
  "Makeup Artist": Sparkles,
  "Mehendi Artist": Hand,
  Caterer: UtensilsCrossed,
  "Cake Designer": Cake,
  DJ: Music2,
  "Live Band": Drum,
  Entertainment: PartyPopper,
  "Wedding Planner": HeartHandshake,
  Transportation: CarFront,
  Accommodation: Hotel,
  "Invitation Designer": Mail,
  "Bridal Wear": Shirt,
  "Groom Wear": Shirt,
  Jewellery: Gem,
  Florist: Flower,
  "Pandit / Priest": Landmark,
  "Event Planner": PartyPopper,
  "Birthday Planner": Cake,
  "Kids Party Planner": Baby,
  "Balloon Decorator": Flower2,
  "Theme Decorator": Sparkles,
  "Kids Entertainer": PartyPopper,
  Magician: WandSparkles,
  "Anchor / Emcee": Mic2,
  Choreographer: Music2,
  "Party Supplies": Boxes,
  "Return Gifts": Gift,
  "Gift Hampers": Package,
  "Sound and Lighting": Volume2,
  "Photo Booth": Camera,
  "Event Security": ShieldCheck,
};

export const CATEGORY_COLOR_MAP: Record<string, string> = {
  Venue: "bg-indigo-500",
  Photographer: "bg-blue-500",
  Videographer: "bg-sky-500",
  Decorator: "bg-pink-500",
  "Makeup Artist": "bg-rose-500",
  "Mehendi Artist": "bg-emerald-500",
  Caterer: "bg-green-500",
  "Cake Designer": "bg-orange-500",
  DJ: "bg-yellow-500",
  "Live Band": "bg-violet-500",
  Entertainment: "bg-red-500",
  "Wedding Planner": "bg-fuchsia-500",
  Transportation: "bg-cyan-500",
  Accommodation: "bg-lime-500",
  "Invitation Designer": "bg-teal-500",
  "Bridal Wear": "bg-purple-500",
  "Groom Wear": "bg-slate-500",
  Jewellery: "bg-amber-500",
  Florist: "bg-green-400",
  "Pandit / Priest": "bg-stone-500",
  "Event Planner": "bg-blue-600",
  "Birthday Planner": "bg-pink-600",
  "Kids Party Planner": "bg-cyan-600",
  "Balloon Decorator": "bg-red-400",
  "Theme Decorator": "bg-violet-600",
  "Kids Entertainer": "bg-yellow-600",
  Magician: "bg-indigo-600",
  "Anchor / Emcee": "bg-sky-600",
  Choreographer: "bg-fuchsia-600",
  "Party Supplies": "bg-slate-600",
  "Return Gifts": "bg-emerald-600",
  "Gift Hampers": "bg-amber-600",
  "Sound and Lighting": "bg-zinc-600",
  "Photo Booth": "bg-blue-500",
  "Event Security": "bg-gray-700",
};
