ALTER TYPE "BookingStatus" ADD VALUE 'ADVANCE_PAID';
ALTER TYPE "BookingStatus" ADD VALUE 'EVENT_COMPLETED';
ALTER TYPE "BookingStatus" ADD VALUE 'AWAITING_ADMIN_REVIEW';
ALTER TYPE "BookingStatus" ADD VALUE 'PAYMENT_APPROVED';
ALTER TYPE "BookingStatus" ADD VALUE 'PAYMENT_HELD';

ALTER TABLE "Booking"
ADD COLUMN "finalPaymentOrderId" TEXT;

ALTER TABLE "Review"
ADD COLUMN "complaint" TEXT,
ADD COLUMN "proofImages" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
