import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fffaf9" },

  headerGradient: {
    paddingTop: Platform.OS === "ios" ? 54 : 40,
    paddingBottom: 18,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerLeft: { flexDirection: "row", alignItems: "center" },
  botIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.25)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.4)",
  },
  headerTitle: { fontSize: 17, fontWeight: "700", color: "#fff" },
  headerSubtitle: { fontSize: 12, color: "rgba(255,255,255,0.85)", marginTop: 1 },
  closeButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(255,255,255,0.25)",
    justifyContent: "center",
    alignItems: "center",
  },

  messageList: { padding: 18, paddingBottom: 8, flexGrow: 1 },

  messageRow: { flexDirection: "row", alignItems: "flex-end", marginBottom: 14 },
  botRow: { justifyContent: "flex-start" },
  userRow: { justifyContent: "flex-end" },

  botAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#ff4d6d",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
    marginBottom: 2,
  },

  messageBubble: {
    maxWidth: "78%",
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 10,
    shadowColor: "#3f1d2f",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 1,
  },
  botBubble: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ffe6eb",
    borderBottomLeftRadius: 4,
  },
  userBubble: {
    backgroundColor: "#ff4d6d",
    borderBottomRightRadius: 4,
  },
  messageText: { fontSize: 14.5, color: "#3f1d2f", lineHeight: 21 },
  userMessageText: { color: "#fff" },

  typingBubble: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },

  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#ffe6eb",
    backgroundColor: "#fff",
  },
  input: {
    flex: 1,
    backgroundColor: "#fff5f6",
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 11,
    fontSize: 14.5,
    color: "#3f1d2f",
    marginRight: 10,
    borderWidth: 1,
    borderColor: "#ffe6eb",
  },
  sendButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#ff4d6d",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#ff4d6d",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 3,
  },
  sendButtonDisabled: {
    backgroundColor: "#ffc2cd",
    shadowOpacity: 0,
    elevation: 0,
  },
});