import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  categoryItem: {
    width: "23%",
    aspectRatio: 1,
    backgroundColor: "rgba(255,255,255,0.94)",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#ffb3bf",
  },
  categoryText: {
    marginTop: 8,
    fontSize: 11,
    fontWeight: "600",
    color: "#3f1d2f",
    paddingHorizontal: 3,
    paddingRight: 4,
    textAlign: "center",
  },
  vendorCard: {
    width: 220,
    backgroundColor: "rgba(255,255,255,0.96)",
    borderRadius: 22,
    overflow: "hidden",
    marginRight: 15,
    borderWidth: 1,
    borderColor: "#ffb3bf",
  },
  vendorImage: { width: "100%", height: 130 },
  vendorHeart: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "#fffef7",
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  vendorTitle: { fontSize: 15, lineHeight: 22, fontWeight: "800", color: "#3f1d2f", paddingRight: 4 },
  vendorRatingRow: { flexDirection: "row", alignItems: "center", marginTop: 4 },
  vendorRating: { fontSize: 12, marginLeft: 4, color: "#3f1d2f", fontWeight: "600" },
  vendorCategory: { fontSize: 12, color: "#8d6171", marginLeft: 4 },
  vendorPrice: { fontSize: 12, color: "#ff4d6d", fontWeight: "700", marginTop: 6 },

  statCard: {
    width: "48%",
    backgroundColor: "rgba(255,255,255,0.94)",
    borderRadius: 22,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#ffb3bf",
    shadowColor: "#ff4d6d",
    shadowOpacity: 0.07,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
    minWidth: 0,
  },
  statIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#ffe6eb",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  statTrendIcon: { position: "absolute", right: 16, top: 16 },
  statTitle: { fontSize: 12, lineHeight: 18, color: "#8d6171", marginTop: 4, paddingRight: 4 },
  statValue: { fontSize: 22, lineHeight: 30, fontWeight: "800", color: "#3f1d2f", marginTop: 3, paddingRight: 4, flexShrink: 1 },
  statLabel: { fontSize: 11, lineHeight: 17, color: "#ff4d6d", fontWeight: "700", marginTop: 3, paddingRight: 4, flexShrink: 1 },

  quickActionCard: {
    width: "48%",
    backgroundColor: "rgba(255,255,255,0.94)",
    borderRadius: 22,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#ffb3bf",
    shadowColor: "#ff4d6d",
    shadowOpacity: 0.07,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  quickActionIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#ffe6eb",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  quickActionTitle: { fontSize: 15, lineHeight: 22, fontWeight: "800", color: "#3f1d2f", paddingRight: 4 },
  quickActionSubtitle: { fontSize: 11, color: "#8d6171", marginTop: 5, lineHeight: 17, paddingRight: 4 },
  quickActionOpenRow: { flexDirection: "row", alignItems: "center", marginTop: 10 },
  quickActionOpen: { fontSize: 12, fontWeight: "700", color: "#ff4d6d", marginRight: 4 },
  
});
