import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  categoryItem: {
    width: "23%",
    aspectRatio: 1,
    backgroundColor: "#fff",
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    elevation: 1,
  },
  categoryText: {
    marginTop: 8,
    fontSize: 11,
    fontWeight: "600",
    color: "#333",
  },
  vendorCard: {
    width: 220,
    backgroundColor: "#fff",
    borderRadius: 20,
    overflow: "hidden",
    marginRight: 15,
    elevation: 1,
  },
  vendorImage: { width: "100%", height: 130 },
  vendorHeart: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "#fff",
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  vendorTitle: { fontSize: 15, fontWeight: "700", color: "#333" },
  vendorRatingRow: { flexDirection: "row", alignItems: "center", marginTop: 4 },
  vendorRating: { fontSize: 12, marginLeft: 4, color: "#333", fontWeight: "600" },
  vendorCategory: { fontSize: 12, color: "#999", marginLeft: 4 },
  vendorPrice: { fontSize: 12, color: "#C2185B", fontWeight: "600", marginTop: 6 },

  statCard: {
    width: "48%",
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 16,
    marginBottom: 14,
    elevation: 1,
  },
  statIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#FDEEF3",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  statValue: { fontSize: 22, fontWeight: "700", color: "#333" },
  statLabel: { fontSize: 12, color: "#C2185B", fontWeight: "600", marginTop: 4 },

  quickActionCard: {
    width: "48%",
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 16,
    marginBottom: 14,
    elevation: 1,
  },
  quickActionIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FDEEF3",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  quickActionTitle: { fontSize: 14, fontWeight: "700", color: "#333" },
  quickActionSubtitle: { fontSize: 11, color: "#999", marginTop: 4, lineHeight: 15 },
  quickActionOpenRow: { flexDirection: "row", alignItems: "center", marginTop: 10 },
  quickActionOpen: { fontSize: 12, fontWeight: "700", color: "#C2185B", marginRight: 4 },
  
});