import { StyleSheet, Dimensions } from "react-native";

const SCREEN_WIDTH = Dimensions.get("window").width;

export const styles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  sidebar: {
    width: SCREEN_WIDTH * 0.8,
    height: "100%",
    backgroundColor: "#FFF5F7",
     flexDirection: "column",
  },
  header: {
    paddingTop: 60,
    paddingBottom: 26,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  userHeader: {
    alignItems: "center",
  },
  avatarCircle: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: "#FF4D6D",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.9)",
    marginBottom: 10,
  },
  avatarInitial: {
    fontSize: 26,
    fontWeight: "800",
    color: "#FFFEF7",
  },
  userName: {
    fontSize: 17,
    fontWeight: "800",
    color: "#3F1D2F",
  },
  userEmail: {
    fontSize: 12,
    color: "#6C2D45",
    marginTop: 2,
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 18,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#B8919F",
    marginBottom: 8,
    marginLeft: 4,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  navList: {
    marginBottom: 18,
  },
  navItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#FFE1E6",
    shadowColor: "#FF4D6D",
    shadowOpacity: 0.06,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  navIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: "#FFE6EB",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  navItemText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#3F1D2F",
  },
  infoList: {
    marginBottom: 10,
  },
  infoItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 8,
  },
  infoIconCircle: {
    width: 28,
    height: 28,
    borderRadius: 10,
    backgroundColor: "#F5F0F2",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  infoItemText: {
    fontSize: 13,
    fontWeight: "500",
    color: "#8D6171",
  },
  divider: {
    height: 1,
    backgroundColor: "#FFE1E6",
    marginVertical: 14,
  },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#FFB3BF",
    paddingVertical: 14,
    marginHorizontal: 16,
    marginBottom: 30,
     marginTop: 8,
  },
  logoutText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#E63B5F",
  },
});